### ISSUE TITLE
Sleep and suspend not working

### ISSUE THREAD

**Issue by Mixss** [Dasharo/dasharo-issues#504] opened 2023-10-10 07:55 UTC
**Dasharo version**

v1.5.0

**Dasharo variant**

novacustom nv4x_tgl and novacustom ns5x_tgl

**Affected component(s) or functionality**

Sleep and suspend

**Brief summary**

On ubuntu:
- after pressing power button (sleep in system settings) or Fn + F12 laptop seems to go to sleep state, but the keyboard stays lit up and green LED is lit up continuously,
- after closing the lid the keyboard goes dark, but the green LED is still lit up continuously,
On Windows:
- there is no 'Sleep' setting available in power buttons settings
- if power button setting is hibernation, then after clicking it the laptop seems to hibernate, but it shuts down. After booting up and going through grub the windows is fresh booted or de-hibernated - it is nondeterministic. One time windows had to boot up from recovery partition after hibernation

**How reproducible**

Always

**How to reproduce**

1. Make sure power settings are set up correctly
2. Sleep/Hibernate

**Expected behavior**

Sleep turns of keyboard light and green LED blinks
Hibernation works

**Actual behavior**

Keyboard stays lit up and green LED is lit up continuously after Sleep
Hibernation shuts the computer completely down

**Comment by mkopec** [comment] 2023-10-11 09:00
> if power button setting is hibernation, then after clicking it the laptop seems to hibernate, but it shuts down. 

that's how S4 sleep generally works, the OS saves its state to the disk and restores it upon wake. need to see it myself on hardware

**Comment by miczyg1** [comment] 2023-10-11 09:13
> if power button setting is hibernation, then after clicking it the laptop seems to hibernate, but it shuts down

Hibernation == shutdown with the OS state saved to disk. When the system is powered on back again, the OS restores its state from disk.

**Comment by mkopec** [comment] 2023-10-11 09:38
> there is no 'Sleep' setting available in power buttons settings

on my machine it's there when s0ix is enabled in the setup menu. when I switch to S3, powercfg reports that neither S3 nor s0ix are supported. Will try with a fresh install - might be a Windows issue

**Comment by miczyg1** [comment] 2023-10-11 11:35
I am not sure if we added S3/S0ix switching for TGL. I believe I have done so, but I may be wrong

**Comment by mkopec** [comment] 2023-10-11 12:24
S3 fixed on NS5x TGL. Need to test on NV4x to confirm that https://github.com/Dasharo/coreboot/pull/295 is no longer needed.

**Comment by mkopec** [comment] 2023-10-11 13:47
Nope, still broken on NV4x TGL.

**Comment by mkopec** [comment] 2023-10-13 09:06
Alright, to summarize, because there are a couple of issues here:

> after pressing power button (sleep in system settings) or Fn + F12 laptop seems to go to sleep state, but the keyboard stays lit up and green LED is lit up continuously,
> after closing the lid the keyboard goes dark, but the green LED is still lit up continuously,

This was caused by S3 not being enabled in mainboard code, but being exposed as an option in the setup menu. Enabled in https://github.com/Dasharo/coreboot/pull/419/commits/3888f9d4a9ce7b6f3430675d1babae16a45ff9b3 , but NV4x TGL has issues waking up (after at most a couple cycles, it fails to even enter bootblock after S3-S0 transition)

May be related to Intel doc #632245 (although that issue affects QS CPUs and was supposedly fixed in production samples)

> there is no 'Sleep' setting available in power buttons settings

Also caused by missing S3, see above

> if power button setting is hibernation, then after clicking it the laptop seems to hibernate, but it shuts down. After booting up and going through grub the windows is fresh booted or de-hibernated - it is nondeterministic. One time windows had to boot up from recovery partition after hibernation

"shutting down" is expected when entering hibernation (S4 state). Question is why Windows doesn't restore its state from disk. For now we do not have a fix for this.

**Closed** 2023-10-16 12:24 UTC
Labels: novacustom_nv4x_tgl, novacustom_ns5x/7x_tgl
