### ISSUE TITLE
V56TNE sometimes does not wake up from suspend

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1018] opened 2024-08-22 05:40 UTC
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc3

### Dasharo Tools Suite version

--

### Test case ID

--

### Brief summary

V56TNE sometimes does not wake up from suspend

### How reproducible

~20%

### How to reproduce

Suspend the device, either using an UI Suspend/Sleep button or by closing the lid

### Expected behavior

The device should suspend and then wake the moment you open the lid, press any internal/external keyboard key, touch/press the touchpad or the power button

### Actual behavior

None of the actions above wake up the device. The power LED is green and blinking suggesting the device is suspended. Connecting via ssh does not work either. The Fn+1 function key does not start up the fans.

### Solutions you've tried

Holding the power button for a couple seconds does power down the device and pressing it after a while results in successful boot.

**Comment by mkopec** [comment] 2024-08-22 10:38
I think this was an issue with the default Ubuntu kernel, installing 6.9.0 mainline works (but breaks nvidia drivers...)

**Comment by wessel-novacustom** [comment] 2024-08-22 11:33
Missing OS and kernel information, it might have happened under Windows?

**Comment by philipandag** [comment] 2024-08-22 12:32
It did happen on 6.8 kernel so that's probably the reason for this. I will again switch to 6.9 kernel to see if that's the case.

**Comment by philipandag** [comment] 2024-08-27 07:06
I haven't noticed any issues with waking up from suspend on kernel 6.9 so that may be the reason for this. But using kernel 6.9 causes the secure boot to fail https://github.com/Dasharo/dasharo-issues/issues/983

**Comment by mkopec** [comment] 2024-10-03 10:33
Also happens on ubuntu 24.10 beta, kernel 6.11, but with 100% reproduction

**Comment by wessel-novacustom** [comment] 2024-10-03 10:53
> Also happens on ubuntu 24.10 beta, kernel 6.11, but with 100% reproduction

Good to know!

I think this is the most important issue now that needs to be tackled.

**Comment by miczyg1** [comment] 2024-10-10 13:28
Tested the ubuntu 24.04 today on V560TNx with kernel 6.8 and it was suspending and waking well using any wake method mentioned in the issue.

> Also happens on ubuntu 24.10 beta, kernel 6.11, but with 100% reproduction

That one is true though. However it was tested on V540TNx, because none of the V560TNx could install 6.11 kernel (nvidia driver dkms was in the way). That's basically all I could do in one day (lost too much time trying to get the right environment prepared on V560TNx...).

It looks a bit weird to have EC communication issues on 6.11 but not on 6.8... managed to get a picture form the screen with some ACPI errors:

![image](https://github.com/user-attachments/assets/5ce420c7-b83a-450e-876d-7961bb5a2800)

**Comment by miczyg1** [comment] 2024-10-10 14:09
More parsable output (managed to gatehr it via SSH session, which I magically restored somehow after suspend): https://paste.dasharo.com/?cf611feda4d8dc91#5yQxEgi48k5Pb7wS3VcAgkXV1ic2hKz31EV1f6ockVrv

The diode is still blinking so EC thinks we are in suspended state...

**Comment by miczyg1** [comment] 2024-10-10 14:31
Attaching a log from S0ixSelftestTool from kernel 6.11:

[20241010-16-22-s0ix-output.log](https://github.com/user-attachments/files/17329710/20241010-16-22-s0ix-output.log)

Surprisingly the tool had no problem with reliably suspending and waking the laptop (although the sleep is scheduled to last 15s only) without breaking EC. But when issued supend from GUI or `echo freeze > /sys/power/state` then it crashes blinking infinitely.

**Comment by mkopec** [comment] 2024-10-14 11:39
Possibly fixed by:
- https://github.com/Dasharo/coreboot/pull/548/commits/29eba1f81f4a94f9923e6f5bb5b30b4508df786b
- https://github.com/Dasharo/coreboot/pull/548/commits/19d804c4ce98f2db4a9afaa0a7abad6e1c7c01f9
Will close once confirmed

**Comment by mkopec** [comment] 2024-10-14 13:37
Confirmed fixed on all units.

**Closed by mkopec** 2024-10-14 13:37 UTC
Labels: bug, firmware, needs review, novacustom_v56_mtl, kernel
