### ISSUE TITLE
OS fails to resume from S3 on some board revisions

### ISSUE THREAD

**Issue by Mixss** [Dasharo/dasharo-issues#523] opened 2023-10-13 12:36 UTC
### Device

NovaCustom TGL

### Dasharo version

v1.5.0

### Affected component(s) or functionality

Sleep (S3) functionality

### Brief summary

When laptop goes to sleep by power button/keyboard shortcut/windows menu 'go to sleep' it is really hard to wake it up. One time it threw out a bluescreen, next time it woke up but there were some graphical bugs

### How reproducible

always

### How to reproduce

1. Turn on S3 in dasharoo
2. Boot into Windows
3. Make sure that power button functionality is set to sleep
4. Press power button
5. Wait for device to be fully asleep
6. Try to wake it up

### Expected behavior

tThe device successfully wakes up

### Actual behavior

Device does not wake up at all or there is a blue screen(VIDEO_TDR_FAILURE). If woke up successfully there were some graphical bugs 
![image](https://github.com/Dasharo/dasharo-issues/assets/19227717/201a81f0-a3f9-4f26-826d-bfd46b972169)

**Comment by Mixss** [comment] 2023-10-13 12:45
"very hard" - after pressing any key then the keyboard is lit and the screen is turned on but stays black. After clicking some keys many times, for example for 30s, then the bluescreen is shown or it wakes up, but with problem for example like in the screenshot above

**Comment by mkopec** [comment] 2023-10-13 13:16
Seems to vary between devices, an NS5x TGL unit on the same bios revision works perfectly with S3.

**Comment by macpijan** [comment] 2023-10-16 21:40
Can we note revisions of these "working" and "not working" mainboards we have tested for future reference?

**Comment by johanes2115** [comment] 2023-10-18 12:21
Suspend (s3) does not properly work on ns70 tgl (sn1.jpg)
It does work on ns50 tgl (sn3.jpg), but with a minor issue.
![sn1](https://github.com/Dasharo/dasharo-issues/assets/43601433/c928a9ca-8435-40c2-9f07-64a4888c5f12)
![sn3](https://github.com/Dasharo/dasharo-issues/assets/43601433/3c5bf213-a291-4e53-9a25-22792ccde8d3)

**Comment by wessel-novacustom** [comment] 2023-11-20 08:00
I found something interesting: S3 wasn't working properly for both Ubuntu and Windows on my NV40MZ-i5 (11th Gen). However, under both Ubuntu and Windows, S3 was working properly (multiple cycles) when attached to a docking station. It wasn't working on battery mode, nor on AC charging mode.

This makes me thinking that the problem might be related to the EC, rather than the main SPI (BIOS).

It's worth mentioning that Windows needed an additional keypress to wake up from S3.

**Comment by wessel-novacustom** [comment] 2023-11-20 08:14
Also interesting: if you try to resume from S3 on battery mode on that platform, the shortcut Fn + 1 (fan speed toggle) no longer works. This might be another indication that the problem is rather EC related?

**Comment by wessel-novacustom** [comment] 2023-11-20 14:43
@mkopec @miczyg1 Does it make sense to further investigate this to try to find a solution for this issue?

If not much chance, we will drop it for now ...

But if this lead to new ideas for a potential solution, please proceed with the investigation before publicly releasing a new firmware version.

**Comment by mkopec** [comment] 2023-11-21 10:52
I dont believe it makes a lot of sense to invest more into this issue, no.

**Comment by wessel-novacustom** [comment] 2024-04-15 16:22
@Mixss Unfortunately, S3 is not supported for all platforms, and not at all for Windows in any case. This is due to hardware limitations and operating systems switching the focus to S0ix modern standby. I suggest to close the issue as it is technically not possible to fix this.

**Closed** 2024-04-16 08:11 UTC
Labels: bug, novacustom_nv4x_tgl, novacustom_ns5x/7x_tgl
