### ISSUE TITLE
asus_kgpe-d16: The fan works at high rpms, close to the initial rpm value after reboot

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#187] opened 2022-09-08 11:13 UTC
**Dasharo version**
v0.4.0

**Dasharo variant**
ASUS KGPE-D16

**Affected component(s) or functionality**
The fan

**Brief summary**
The fan works at high rpms, close to the initial rpm value after reboot on ASUS KGPE-D16

**How reproducible**
100% 

**How to reproduce**

1. Power on the DUT.
2. Boot into Ubuntu.
3. Install package `lm-sensors`
4. In the terminal window run the following command: `sensors | grep fan1`
5. Repeat command every one minute, for some time.

**Expected behavior**
The fan doesn't work on rpms closed to initial rpm value. (1000-2000 RPM)

**Actual behavior**
The fan works on rpms closed to initial rpm value. (~6995 RPM)

**Screenshots**

**Additional context**
The first boot logs after the reboot command appear after around 1 minute.

**Solutions you've tried**

**Comment by krystian-hebel** [comment] 2022-09-08 11:27
Duplicate of https://github.com/Dasharo/dasharo-issues/issues/169

**Closed by krystian-hebel** 2022-09-08 11:27 UTC
Labels: asus_kgpe-d16
