### ISSUE TITLE
WiFi adapter not found when scanning for network in Ubuntu

### ISSUE THREAD

**Issue by JanPrusinowski** [Dasharo/dasharo-issues#1107] opened 2024-10-24 12:51 UTC
### Component

Dasharo firmware

### Device

Protectli VP3230

### Dasharo version

v0.9.0-rc2

### Dasharo Tools Suite version

develop

### Test case ID

WLE002.001 Wi-Fi scanning (Ubuntu)

### Brief summary

WiFi adapter not found when scanning for network in Ubuntu

### How reproducible

100%

### How to reproduce

Boot machine to Ubuntu
Login as root
Execute:
`lspci | grep "Network controller:"` to verify if the network controller exists in the platform. you should receive: `3:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev ff)`

`nmcli radio wifi on`
`nmcli device wifi rescan`

you will recieve: `Error: No Wi-Fi device found.`

### Expected behavior

after waiting for a few seconds and executing: `nmcli device wifi list` a list of networks should be displaeyd

### Actual behavior

`Error: No Wi-Fi device found.`

### Screenshots

![image](https://github.com/user-attachments/assets/44eca000-6327-45c3-b5da-898418a3edd5)
[log - WLE.zip](https://github.com/user-attachments/files/17507054/log.-.WLE.zip)

### Additional context

Under windows there is no problem with detecting the adapter and scanning for networks.

**Comment by krystian-hebel** [comment] 2024-10-29 16:51
This may or may not be the same as https://github.com/Dasharo/dasharo-issues/issues/961.

**Comment by miczyg1** [comment] 2024-10-30 11:04
Could also be Wifi card FW issue: https://kb.protectli.com/kb/wifi-on-the-vault/#articleTOC_5

**Comment by krystian-hebel** [comment] 2024-10-31 13:35
Yep, it was a card marked as 2145 so it probably was caused by wrong FW. Unfortunately, from the OS both revisions look identical, so it isn't possible to differentiate between them remotely, other than by trial and error.

**Comment by miczyg1** [comment] 2024-11-07 09:24
Dmesg would tell us what went wrong. But it isn't probably Dasharo's fault. Just software/driver/card FW fault that the card is not operable in OS.

**Comment by SebastianCzapla** [comment] 2024-12-05 10:10
[wifi-scanning.zip](https://github.com/user-attachments/files/18021362/wifi-scanning.zip)

Issue no longer present on Ubuntu when testing rc4, however scans on Windows yield no device

**Comment by miczyg1** [comment] 2024-12-09 14:34
On rc4 seems to work well:

![image](https://github.com/user-attachments/assets/d73aa1b0-843c-41fe-8c7c-f4b0f871f40c)

**Closed** 2024-12-11 13:21 UTC
Labels: bug, firmware, needs review, protectli_vault_adln
