### ISSUE TITLE
After emergency shutdown, keyboard doesn't work before OS NV41MZ v1.3.0

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#199] opened 2022-09-23 06:44 UTC
**Dasharo version**
v1.3.0

**Dasharo variant**
NV41MZ

**Affected component(s) or functionality**
The keypad, power off using the power button

**Brief summary**
After power off using the power button, the keypad doesn't work in BIOS and GRUB

**How reproducible**
100% - when using the power button in OS (Ubuntu 22.04, Windows 11)
~70% - when using the power button in BIOS
0% - when using the power button before login to Ubuntu 22.04

**How to reproduce**

1. Power on the DUT.
2. Use the power button in OS/BIOS to power off the DUT.
3. Use the power button again to power on the DUT.
4. Try to use keypad in BIOS or GRUB.

**Expected behavior**
The keypad works in BIOS and GRUB.

**Actual behavior**
The keypad didn't work in BIOS and GRUB

**Screenshots**

**Additional context**
The external keyboard always works.
The keyboard starts working when the OS boot.

**Solutions you've tried**

**Comment by macpijan** [comment] 2022-09-23 07:51
@Pokisiekk Do we have the NS50 with v1.3.0 on hand to see whether it is applicable also here? It might be helpful to locate the source of the problem.

**Comment by Pokisiekk** [comment] 2022-09-23 08:19
@macpijan I did some tests on NS70MU with v.1.3.0 (same firmware as NS50), but only on Ubuntu 22.04 and I didn't experience similar problems.

**Comment by mkopec** [comment] 2022-09-26 11:31
By power off using power button, do you mean holding down the power button until the laptop shuts off, or pressing it shortly allowing the OS to shut down properly?

**Comment by Pokisiekk** [comment] 2022-09-26 11:33
@mkopec I mean holding down the power button until the laptop shuts off

**Comment by mkopec** [comment] 2022-09-26 11:43
Confirmed reproduction on one NV41MB (silver) laptop. Could not reproduce on another NV40MB (black) laptop, which ma have a newer board revision. Also need to check if issue happens with ISO and ANSI keyboards.

**Comment by mkopec** [comment] 2022-09-26 11:56
Swapped the keyboards and now neither laptop exhibits this issue. Very weird

**Comment by miczyg1** [comment] 2022-12-15 11:36
I also noticed it on NS70PU when I was playing with Qubes OS. Sometimes the keyboard did not simply work after power state changes (reboots/resets/poweroffs). I didn't do any serious testing so I did not note which power transitions caused the problem (power button, poweroff from OS etc.)

**Comment by macpijan** [comment] 2023-02-24 15:07
This is a duplicate of: https://github.com/Dasharo/dasharo-issues/issues/295
The linked issue has more precised naming of the problem. Although the exact reason of trigerring the issue is not known as of now.

**Closed by macpijan** 2023-02-24 15:07 UTC
Labels: bug, novacustom_nv4x_tgl
