### ISSUE TITLE
Please answer my old question; were users who experienced #556 owned?

### ISSUE THREAD

**Issue by sycam0r-e** [Dasharo/dasharo-issues#689] opened 2024-01-26 17:00 UTC
Recently, there was this mysterious blue screen for a few users after updating, see [#556](https://github.com/Dasharo/dasharo-issues/issues/556).

In that issue, I asked [two](https://github.com/Dasharo/dasharo-issues/issues/556#issuecomment-1838530372) [times](https://github.com/Dasharo/dasharo-issues/issues/556#issuecomment-1853793619) "under which conditions (e.g. if the iPXE boot menu has been used) users do not have to worry". Sadly, this hasn't been answered, while the issue has been closed. This is very irritating.

@pietrushnic from my POV adequatly commented that "Fixing [that issue] is one thing, but correctly communicating such a scary message may pop up is another. IT would be great if we can address both, because this bug **really damage (sic) Novacustom and Dasharo reputation**." (emphasis added).

I still want to know under which circumstances that error message can be ignored and how one could recover or make sure to be safe. I don't like that this has been ignored so far.

**Comment by pietrushnic** [comment] 2024-01-26 21:54
@sycam0r-e, thanks for being patient and pointing us again to that. 

@BeataZdunczyk @macpijan From the beginning of that problem, I tried to get information under what conditions this happened. At some point in PRs, we had flow diagrams with designs linking such algorithms in documentation, which should be the minimum we can do. Trying to explain that in relatively simple language would be next level, and not allowing such a design, which essentially scares people out without reason, would be a wonderful guideline for Dasharo.

This is a critical message that should be addressed:

> So, we implemented a protection mechanism with poor detection quality (many false positives) and no recovery. Every design of security features should treat all stages of protection, detection, and recovery equally seriously.

@macpijan mentioned that false positives were not proven, and despite no definitive action against IMHO, the flawed design issue was closed. We need a better UX for this feature.

**Comment by pietrushnic** [comment] 2024-02-08 11:17
> The screen simply says the recovery partition was used on this particular boot, so even if the verification failed, the "untrusted" firmware was not executed. If the screen would appear on subsequent boots, it would mean that still for some reason recovery partition is used.

@macpijan IMHO, this is a critical part that was not communicated to users. I think we should have FAQ or feature description section in documentation which precisely say what you explained here.

**Comment by mkopec** [comment] 2024-03-06 18:06
Regarding the issue with the popup:

![image](https://github.com/Dasharo/dasharo-issues/assets/3678707/bce462ca-4d9a-4339-9a4d-6cba4b6eaba1)

No, if your laptop displayed the popup above - and did it once and it disappeared after a reboot - you were not owned.

The next firmware release will contain a fix for this: https://github.com/Dasharo/coreboot/pull/465

---

It was caused by incorrect usage of TPM secdata - anti-rollback and checksum data that gets invalidated when we perform updates of the bootblock / Vboot recovery section (which, as it turns out, we need to do with every update). In short, it is a part of Vboot's code that suits the ChromeOS security model (permanent WP) but does not work for us and can cause erroneous recovery entry (thus the warning popup).

It was extremely difficult to reproduce for us, in fact the popup seemed to appear once per every affected device, which is why it took so long to pin down.

**Closed** 2024-03-11 10:08 UTC
