### ISSUE TITLE
The fan starts to spin only above 80°C NV41Mx v1.3.0

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#200] opened 2022-09-23 11:19 UTC
**Dasharo version**
v1.3.0

**Dasharo variant**
NV41Mx

**Affected component(s) or functionality**
The fan

**Brief summary**
The fan starts to spin only above 80°C.

**How reproducible**
100%

**How to reproduce**

1. Do test `FAN001.001` from [documentation](https://docs.dasharo.com/unified-test-documentation/dasharo-compatibility/S30-fan-control/)

**Expected behavior**
The fan starts to spin only above 40°C.
The fan stops to spin only below 40°C.

**Actual behavior**
The fan starts to spin only above 80°C.
The fan stops to spin only below 80°C.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by macpijan** [comment] 2022-09-23 12:17
@mkopec I believe that the desired fan curve was simply not moved from the devicetree (as it was defined there when the proprietary EC was in use) to EC firmware here: https://github.com/Dasharo/ec/blob/master/src/board/system76/galp5/board.mk#L40

**Comment by macpijan** [comment] 2022-09-23 12:18
Moreover, the documentation is not up to date. The desired fan curve should be as was implemented here:
https://github.com/Dasharo/coreboot/pull/204/files

**Comment by macpijan** [comment] 2022-09-26 13:10
@Pokisiekk 
 Why is it closed with no comments?

**Comment by Pokisiekk** [comment] 2022-09-26 13:24
The reported problem was caused by the lack of a documentation update. The described behavior of the fan is correct.

**Comment by Pokisiekk** [comment] 2022-09-26 13:24
The reported problem was caused by the lack of a documentation update. The described behavior of the fan is correct.

**Comment by macpijan** [comment] 2022-09-26 13:36
I do not think it was correct, @mkopec ?

**Comment by mkopec** [comment] 2022-09-26 13:38
According to code the fan will start spinning at 70 degC. There is some smoothing implemented so the fan may start spinning at a higher temperature and stop spinning at a lower temperature. I have a fix but I need to test it first

**Comment by mkopec** [comment] 2022-09-26 15:11
PR: https://github.com/Dasharo/ec/pull/7

Had to raise the minimum fan speed, since one of the fans in the unit I tested was stalling at 16%.

**Comment by mkopec** [comment] 2022-10-11 12:57
PR merged, confirmed fixed. closing.

**Closed by mkopec** 2022-10-11 12:57 UTC
Labels: clevo_nv41mz
