### ISSUE TITLE
Fan of the 2nd CPU is running at full speed

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#412] opened 2023-04-18 12:51 UTC
**Dasharo version**

**Dasharo variant**

**Affected component(s) or functionality**

**Brief summary**

**How reproducible**

**How to reproduce**

1. 
2. 
3. 

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by macpijan** [comment] 2023-04-18 12:52
It comes from: https://github.com/Dasharo/dasharo-issues/issues/35#issuecomment-1505630042

@krystian-hebel Please edit this issue (or provide details in the comment, if cannot edit) once you get your hands on this and reproduce the problem on our side.

**Comment by SergiiDmytruk** [comment] 2023-07-14 17:33
This is a duplicate of #416 where all the discussion happened, so closing.

**Closed by SergiiDmytruk** 2023-07-14 17:33 UTC
Labels: raptor-cs_talos-2
