### ISSUE TITLE
Longer life for batteries

### ISSUE THREAD

**Issue by micmarluc** [Dasharo/dasharo-issues#285] opened 2022-12-14 13:49 UTC
**The problem you're addressing (if any)**
Currently, it is not possible to limit the battery charge when the computer is plugged into the mains (for all users)

**Describe the solution you'd like**
Add a firmware option (if possible) to limit the battery charge for example to 80% - with the possibility to go back to 100% if necessary.

**Where is the value to a user, and who might that user be?**
More savings and less pollution for everyone

**Describe alternatives you've considered**

**Additional context**

**Comment by macpijan** [comment] 2023-01-25 10:11
Hello @micmarluc 
Thanks for the report. It would be nice to provide more details on what device are you referring to. 
I assume it is one of the NovaCustom laptops.

**Comment by micmarluc** [comment] 2023-01-25 20:47
Hello @**macpijan**
Sorry for forgetting !
Indeed, it is a NovaCustom laptop : NS70.

**Comment by micmarluc** [comment] 2023-01-29 08:52
Hello @macpijan 
1/ More details about my laptop :  NovaCustom NS70MU i5-1135G7
2/ Please, can you add the label "enhancement", I did not understand how to do it. I searched in the GitHub documentation (managing labels), but I can’t find any right sidebar that gives me access to the settings. Thank you

**Comment by pietrushnic** [comment] 2023-01-29 20:46
@micmarluc I guess that only organization members can add labels.

**Comment by UndeadDevel** [comment] 2024-01-11 18:12
This seems like a duplicate of #246 but FWIW having this option is indeed very much desired; I'm using Heads from NitroKey and on their 2.1 release (~June 2023) the system exposed `/sys/class/power_supply/BAT0/charge_control_end_threshold` and `/sys/class/power_supply/BAT0/charge_control_start_threshold`, which allowed to manually set the charge limits. Now I upgraded to version 2.4 (based on coreboot 1.7.2) and those files have disappeared such that now there doesn't seem to be the possibility of setting charge limits any more.

**Comment by pietrushnic** [comment] 2024-01-11 21:49
> Now I upgraded to version 2.4 (based on coreboot 1.7.2) and those files have disappeared such that now there doesn't seem to be the possibility of setting charge limits any more.

Currently, we do not support Dasharo (coreboot+Heads) on Novacustom. Saying that issues regarding Nitrokey releases should go to the Nitrokey repository.

Of course, we are working on enabling Dasharo (coreboot+Heads) and hope to deliver this month. I'm not sure what else we can do right now. @macpijan cc

**Comment by UndeadDevel** [comment] 2024-01-12 12:32
Ok, I already [reported it](https://github.com/Nitrokey/heads/issues/35) at their issue tracker; I just thought that this is probably an upstream issue with coreboot, but I could be wrong about that.

**Comment by wessel-novacustom** [comment] 2024-04-15 14:47
@micmarluc The feature [has been implemented](https://docs.dasharo.com/unified/novacustom/battery-management/#charge-thresholds). Could you close the issue, please?

**Closed** 2024-04-15 18:32 UTC
Labels: enhancement

**Comment by tlaurion** [comment] 2024-04-22 00:55
@macpijan @wessel-novacustom clksed too soon?

https://github.com/linuxboot/heads/issues/1647#issuecomment-2068293817

**Comment by tlaurion** [comment] 2024-04-24 23:36
Should reopen until https://github.com/Dasharo/dasharo-issues/issues/820 fixed

**Comment by macpijan** [comment] 2024-04-25 08:54
It is implemented in the firmware for the UEFI firmware variant.
