### ISSUE TITLE
Internal keyboard sometimes does not work in firmware

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#295] opened 2022-12-20 10:47 UTC
**Dasharo version**
v1.4.0

**Dasharo variant**
NS5x/7xPU

**Affected component(s) or functionality**
internal keyboard

**Brief summary**
Internal keyboard stops working in BIOS after pressing `ESC` many times.

**How reproducible**
~7%

**How to reproduce**

1. Power on the DUT.
2. Press the `ESC` button as fast as possible. 

**Expected behavior**
Setup menu is displayed. Internal keyboard works.

**Actual behavior**
Setup menu is displayed. Internal keyboard does not work.

**Comment by 3mdeb-karolzmyslowski** [comment] 2023-02-15 13:06
The same problem with NV41PZ, Dasharo 1.4.0.
Problem is not even with entering to setup, but also in choosing one-time boot device.

**Comment by wessel-novacustom** [comment] 2023-03-10 08:43
Will this be solved in next firmware releases? So far, we have only seen this bug for Alder Lake devices.

**Comment by wessel-novacustom** [comment] 2023-03-10 08:44
A way to workaround this bug:

1. Shut down the laptop.
2. Remove the power supply for at least 10 seconds.
3. Re-attach the power supply and startup the laptop again.

**Comment by newbieVR** [comment] 2023-03-10 10:25
I can confirm that the keyboard is deactivated with the Dasharo Version 1.4.0 when you press the <ESC> button very early or multiple times after you turned on the laptop. Then it is impossible to navigate in the setup, in one time boot or in the Dasharo Toolsuite.

The comment of Mr. Wessel is the only possibility to get into the setup, on time boot or Dasharo toolsuite after the keyboard is deactivated.

**Comment by Pokisiekk** [comment] 2023-03-10 11:29
@wessel-novacustom After testing the NV41Mx and NS5x/7xMU with Dasharo firmware v1.4.0, I noticed a few cases where I couldn't get to the setup or boot menu due to the keyboard not working. There is no one specific scenario after which this happens, but I can say that it definitely occurs after turning off the device using the power button, which I described in [this issue](https://github.com/Dasharo/dasharo-issues/issues/199).

**Comment by miczyg1** [comment] 2023-03-10 17:31
Set of PRs fixing this on ADL laptops:

https://github.com/Dasharo/coreboot/pull/317
https://github.com/Dasharo/edk2/pull/53
https://github.com/Dasharo/ec/pull/32

**Comment by Pokisiekk** [comment] 2023-04-07 11:21
[Here](https://docs.dasharo.com/variants/novacustom_ns5x_adl/releases/#v160-2023-04-07) are the binaries in version v.1.6.0 for NS5x/7x ADL, on which the issue does not occur

**Comment by XGIVolari** [comment] 2023-04-07 18:51
Unfortunately I just ran into this issue on v1.6.0. (NS5x/7xPU) Disconnecting the power supply does not fix it, and neither does disconnecting the internal battery. Special keys like turning the display on/off still work, but no sign of life from any actual keyboard inputs inside the firmware setup menu. Since this first occured, it has happened on every boot meaning that I am effectively locked out of the firmware setup.

**Comment by XGIVolari** [comment] 2023-04-07 19:49
This happened after restoring default settings with F9, seems to be the same as #355.

**Comment by wessel-novacustom** [comment] 2023-04-08 10:10
> Unfortunately I just ran into this issue on v1.6.0. (NS5x/7xPU) Disconnecting the power supply does not fix it, and neither does disconnecting the internal battery. Special keys like turning the display on/off still work, but no sign of life from any actual keyboard inputs inside the firmware setup menu. Since this first occured, it has happened on every boot meaning that I am effectively locked out of the firmware setup.

@XGIVolari Thanks for reporting this. We will try to reproduce this. FWIW: it should still be possible to access the firmware settings with an external keyboard.

**Comment by XGIVolari** [comment] 2023-04-08 13:59
@wessel-novacustom Thank you for replying to me on the weekend. External keyboards don't seem to function either. I've checked all USB ports + USB-C ones with an externally powered adapter. 

Next thing I'm going to try is if reflashing the firmware helps (and if I can convince GRUB to chainload the DTS USB image)

**Comment by wessel-novacustom** [comment] 2023-04-08 14:13
Thank you.
> Next thing I'm going to try is if reflashing the firmware helps (and if I can convince GRUB to chainload the DTS USB image)
- Yes please.
I tried to reproduce the issue, but I couldn't. In DTS, when dropping a Shell (option 9) and running ` system76_ectool info`, does it return a version info of this year; 2023? This would indicate that the EC firmware update has succeeded. Otherwise, the EC update seems to be failed.

**Comment by XGIVolari** [comment] 2023-04-09 08:17
Reflashing the firmware image seems to have no effect. system76_ectool returns `board: novacustom/ns5x_adl version: 2023-03-20_c398446` which looks sane I think. Below is the full DTS HCL report. I've also added the output from the coreboot memory console found under /sys/firmware/log as a file called firmware.log. 
I should also note that before restoring the settings, I had tried out both of the new ME neutering options. Maybe something went wrong there?

[Notebook_NS5x_NS7xPU_Dasharo_(coreboot+UEFI)_v1.6.0_adb958f1-0783-5a2d-8e0a-4474b50d0300_2023_04_09_04_49_30_566754197.zip](https://github.com/Dasharo/dasharo-issues/files/11185029/Notebook_NS5x_NS7xPU_Dasharo_.coreboot%2BUEFI._v1.6.0_adb958f1-0783-5a2d-8e0a-4474b50d0300_2023_04_09_04_49_30_566754197.zip)

**Comment by XGIVolari** [comment] 2023-04-09 11:19
Update: I managed to resolve the issue by rolling EFI/EC FW back to 1.4.0 and flashing 1.6.0 again.

**Comment by miczyg1** [comment] 2023-04-11 08:54
Restoring defaults with F9 is broken right now, so it would be best to avoid using this. It can cause a lockout and only reflashing the release image may help.

**Comment by sulewskiprzemyslaw** [comment] 2023-04-20 07:49
@Pokisiekk Fix for this bug for NV4x ADL has been added in firmware [v1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/#v160-2023-04-19)

**Comment by Ferenc-** [comment] 2023-10-08 14:56
Hi,
NS 51 TGL user here. With `v1.4.0`, the built-in keyboard can never be used for entering the bios `F2` or  the boot menu  `F7`.
An external USB keyboard does work as a work around, yet this is very annoying.
@miczyg1 I see the ADL fixes are pretty old, are there TGL fixes as well?

**Comment by miczyg1** [comment] 2023-10-10 08:31
@Ferenc- I do not see the fix integrated into TGL build configs, so this issue is most likely still applicable for TGL devices.

**Comment by miczyg1** [comment] 2023-10-10 10:26
I have ensured the fix will land in v1.5.0: when the PR is merged https://github.com/Dasharo/coreboot/pull/419/commits/da5e602b5cda5af4c61de87866e2918c39abcab3

**Comment by Ferenc-** [comment] 2023-10-10 11:50
> I have ensured the fix will land in v1.5.0: when the PR is merged [Dasharo/coreboot@da5e602](https://github.com/Dasharo/coreboot/commit/da5e602b5cda5af4c61de87866e2918c39abcab3)

Thank you @miczyg1. Is this [v1.5.0 tag](https://github.com/Dasharo/coreboot/releases/tag/novacustom_ns5x_tgl_v1.5.0) in that repo, not the same `v1.5.0`?

**Comment by wessel-novacustom** [comment] 2023-12-12 18:12
I believe this has been solved now and should therefore be closed (?).

**Comment by wessel-novacustom** [comment] 2024-04-15 14:49
@Pokisiekk This issue has been solved with the latest firmware releases, please close the issue.

**Closed** 2024-06-28 19:08 UTC
Labels: bug, novacustom_nv4x_tgl, novacustom_ns5x/7x_tgl, novacustom_ns7x_tgl
