### ISSUE TITLE
Platform fails to resume from S3 suspend (Ubuntu 22.04)

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#554] opened 2023-10-30 17:11 UTC
### Device

Novacustom nv41 TGL

### Dasharo version

v1.5.0

### Affected component(s) or functionality

Suspend and resume

### Brief summary

Sometimes while trying to wake the platform up from sleep with S3 suspend mode selected, results in the device rebooting. Other times, the keyboard and power diode will light up, but there won't be power to the display.

### How reproducible

Random

### How to reproduce

1. Power on the device
2. Enter BIOS setup
3. Go to `Dasharo System Features` -> `Power Management Options`
4. Select S3 suspend mode and save the settings
5. Reset the device
6. Boot into Ubuntu 22.04
7. Suspend the device
8. Try to wake it up from suspend by pressing any keyboard key

### Expected behavior

The device wakes up from suspend.

### Actual behavior

The device reboots or gets stuck with unlit display.

### Additional context

No image on external display either in case of the second problem mentioned in summary.

**Comment by MasterBootRecord32** [comment] 2023-10-31 11:06
I can reproduce this issue on my NV40MZ under Arch Linux + GNOME using the S3 suspend mode.

**Comment by wessel-novacustom** [comment] 2023-11-01 17:32
I can reproduce this issue on my NV40MZ under Ubuntu + GNOME using S3, alongside another [critical issue](https://github.com/Dasharo/dasharo-issues/issues/555).

Our firmware developers are working on this issue now and a hotfix release will be published very soon.

**Comment by mkopec** [comment] 2023-11-02 15:07
This is related to the problems I saw during development:

> I am sometimes able to randomly able to complete a number of S3 cycles this but after a reboot the issue comes back. Most often the laptop is able to do two S3 cycles correctly but hangs on the third, but that's not very consistent either.

There is an issue with the CPU not coming back online at all, no logs are even produced. May be related to ME version, some missing initialization, or incorrect signal timing in EC firmware.

**Comment by wessel-novacustom** [comment] 2023-11-14 16:36
I can try a newer ME version with some different configuration tomorrow if you could provide me a binary, @mkopec.

Also, some revisions of NS5 12th Gen have no hardware support for S3.

**Comment by mkopec** [comment] 2023-11-16 11:56
After updating the ME to 15.0.47.2473v3 and clearing the CMOS i was able to get 12 S3 cycles to complete successfully, but after a reboot the issue would always come back. So it looks like when ME finishes init after the first boot, the problem begins to re-appear, so it's definitely related to the ME. Unfortunately multiple versions of ME exhibit the problem. I also tried setting the ME debug flags to 0x00000007 to disable some of the timeouts but that didn't help either.

At this point it really looks like S3 is unsupported on this platform. S3 working on NS5x TGL at all is probably a happy accident.

**Comment by wessel-novacustom** [comment] 2023-11-20 08:02
Related comment: https://github.com/Dasharo/dasharo-issues/issues/523#issuecomment-1818409641

**Comment by wessel-novacustom** [comment] 2024-04-15 16:22
@johanes2115 Unfortunately, S3 is not supported for all platforms. This is due to hardware limitations and operating systems switching the focus to S0ix modern standby. I suggest to close the issue as it is technically not possible to fix this.

**Closed** 2024-04-16 08:12 UTC
Labels: bug, novacustom_nv4x_tgl
