### ISSUE TITLE
Add ACPI thermal monitoring and fan control

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#148] opened 2022-06-17 16:17 UTC
**The problem you're addressing (if any)**

There is currently no user-friendly way to monitor temperatures and fan speeds from within the OS

**Describe the solution you'd like**

Add ACPI thermal zones and fan devices, so that fan speeds and temperatures can be easily monitored.

**Where is the value to a user, and who might that user be?**

Thermal monitoring and fan control are useful for users who want to be able to monitor their devices' thermals and control fan speeds
to their liking (e.g. to minimize noise or maximize performance)

**Describe alternatives you've considered**

**Additional context**

- ACPI Fan device spec: https://uefi.org/specs/ACPI/6.4/11_Thermal_Management/fan-device.html
- ACPI Thermal control spec: https://uefi.org/specs/ACPI/6.4/11_Thermal_Management/thermal-control.html

**Comment by miczyg1** [comment] 2022-06-20 08:47
@mkopec add labels for the laptops?

**Comment by mkopec** [comment] 2022-06-20 14:14
though arguably the same applies to desktops/workstations and all other form factors

**Comment by miczyg1** [comment] 2022-06-21 09:38
Indeed it is. It all boils down how good we know the chip controlling the fans...

**Comment by wessel-novacustom** [comment] 2024-04-15 14:19
Would be nice if we can have this for the next firmware versions.

It used to be present in previous open EC versions, but not any longer since the latest firmware versions.

**Comment by rapenne-s** [comment] 2024-04-17 15:46
This would be definitely be useful to have more hardware information on systems.

**Comment by PeterLacknase** [comment] 2024-04-17 17:50
Dito.

**Comment by wessel-novacustom** [comment] 2024-04-17 19:05
@macpijan Please plan this for the upcoming releases, if possible.

**Comment by wessel-novacustom** [comment] 2024-07-30 07:23
Duplicate of #820, I would close this issue and track the issue further there.

**Closed** 2024-07-30 07:55 UTC
Labels: enhancement, novacustom_nv4x_tgl, novacustom_ns5x/7x_tgl, novacustom_ns7x_tgl
