### ISSUE TITLE
CPU fequency stuck on 2600 Mhz

### ISSUE THREAD

**Issue by PrzemyslawBanasiak13** [Dasharo/dasharo-issues#290] opened 2022-12-19 14:33 UTC
**Dasharo version**
v1.0.0

**Dasharo variant**
Protectli VP2420

**Affected component(s) or functionality**
CPU frequency

**Brief summary**
CPU frequency is stuck on 2600 Mhz frequency on Ubuntu 22.04

**How reproducible**
100%

**How to reproduce**

1. Boot the device
2. Boot to ubuntu 22.04
3. Check CPU frequency using `cat /proc/cpuinfo | grep -i mhz` in terminal

**Expected behavior**
The frequency of at least one core is different than 2600 Mhz

**Actual behavior**
CPU frequency is stuck on 2600 Mhz

**Comment by miczyg1** [comment] 2022-12-19 14:41
@PrzemyslawBanasiak13 would be great to have the output of the mentioned command attached here

**Comment by PrzemyslawBanasiak13** [comment] 2022-12-19 14:49
Example output of `cat /proc/cpuinfo | grep -i mhz` command:

```
cpu MHz		: 2600.000
cpu MHz		: 2599.999
cpu MHz		: 2600.000
cpu MHz		: 2600.000
```

**Comment by miczyg1** [comment] 2022-12-19 16:03
@PrzemyslawBanasiak13 the issue does not reproduce. On the Ubuntu that was left on eMMC I have:

```
cpu MHz		: 2000.000
cpu MHz		: 2000.000
cpu MHz		: 2000.000
cpu MHz		: 792.435
```

The frequency is jumping up and down on all cores when doing `watch -n 1 "cat /proc/cpuinfo |grep -i mhz"`

**Comment by miczyg1** [comment] 2022-12-19 16:06
Also the frequency caps at 2600MHz when the CPU is being stressed with `stress-ng` for example which is expected behavior. I will rebuild the firmware so that it does not print coreboot debug messages on serial. Seems something is off with this binary, so will recheck on the newly built one as well

**Comment by miczyg1** [comment] 2022-12-19 17:53
After fiing other issues and rebuilding the binary as it should be the issue is not present. Checked with DTS v1.1.0 and the cores are either at 2GHz and jumping to lower frequency.

**Comment by sulewskiprzemyslaw** [comment] 2022-12-21 13:00
@miczyg1 @PrzemyslawBanasiak13 I just changed the labels of the issue. Currently,  we are not sure whether the problem found is related to firmware, incomplete support for the processor on Ubuntu, or perhaps it is the correct idle behavior

**Comment by macpijan** [comment] 2023-02-02 09:25
This is rather a problem regarding the test procedure using incorrect tools for the job, or the tools itself. @sulewskiprzemyslaw please update and/or close this once we have more information.

**Comment by macpijan** [comment] 2024-03-26 15:44
@filipleple Do you have results of this on the 1.2.0?

**Comment by filipleple** [comment] 2024-03-26 15:54
@macpijan on the 1.2.0 it doesn't get stuck on initial frequency, but then it doesn't run on expected frequency either. I've mentioned it and linked the logs in https://github.com/Dasharo/dasharo-issues/issues/763

**Comment by miczyg1** [comment] 2024-04-03 11:31
Doing `stress-ng --cpu 8 --io 4 --vm 2 --vm-bytes 128M --fork 4 --timeout 10s &` on Ubuntu and then watching `watch -n 1 "cat /proc/cpuinfo |grep -i mhz"` returns all cores at 2600Mhz which is max for this CPU. When idling, all cores are at 800MHz, which is the lowest for this core.

All seem to be correct on v1.2.0

**Closed** 2024-06-28 19:08 UTC
Labels: invalid, protectli_vault_ehl
