### ISSUE TITLE
 Reset to defaults with F9 causes the wrong settings to be restored

### ISSUE THREAD

**Issue by sulewskiprzemyslaw** [Dasharo/dasharo-issues#355] opened 2023-02-28 09:58 UTC
**Dasharo version**

v1.1.1

**Dasharo variant**

msi_ms7d25

**Affected component(s) or functionality**

Reset to defaults with F9

**Brief summary**

Using the F9 key to restore the default settings causes incorrect parameter settings to be entered.

All examples:
1. `USB stack enabled` - using F9 sets that option to `Disabled`, when the true default setting is `Enabled`.
2. `Lock the BIOS boot medium` - using F9 sets that option to `Disabled`, when the true default setting is `Enabled`.
3. `Enable USB Mass Storage driver` - using F9 sets that option to `Disabled`, when the true default setting is `Enabled`.
4. `Enable PS2 controller` - using F9 sets that option to `Disabled`, when the true default setting is `Enabled`.
5. `Enable watchdog` - using F9 sets that option to `Disabled`, when the true default setting is `Enabled`.
6. `Watchdog timeout value` - using F9 sets that option to `90`, when the true default setting is `120`.

**How reproducible**

Always

**How to reproduce**

1. Enter the Setup menu by using the proper key.
3. Enter any submenu of Dasharo System Features.
4. Use the F9 key to restore the default settings.
5. Confirm restring the default settings.
6. Check the status of the parameters in all of the 'Dasharo system features` submenu. 

**Expected behavior**

1. `Enable USB stack` should be marked as active after resetting default settings.
2. `Lock the BIOS boot medium` should be marked as active after resetting default settings.
3. `Enable USB Mass Storage driver` should be marked as active after resetting default settings.
4. `Enable PS2 controller` should be marked as active after resetting default settings.
5. `Enable watchdog` should be marked as active after resetting default settings.

**Actual behavior**

1. `Enable USB stack` is marked as inactive after resetting default settings.
2. `Lock the BIOS boot medium` is marked as inactive after resetting default settings.
3. `Enable USB Mass Storage driver` is marked as inactive after resetting default settings.
4. `Enable PS2 controller` is marked as inactive after resetting default settings.
5. `Enable watchdog` is marked as inactive after resetting default settings.

**Screenshots**

**Additional context**

**Solutions you've tried**

Reproduce the issue a couple of times (first, flash the device externally, then use F9 again).

**Comment by Pokisiekk** [comment] 2023-02-28 13:12
NS5x/7xMU v1.4.0 dasharo firmware: Reset to defaults with F9 makes it impossible to enter the bios/setup menu and change settings

**Comment by macpijan** [comment] 2023-02-28 14:18
> Reset to defaults with F9 makes it impossible to enter the bios/setup menu and change settings

Why? What is the exact problem?
Are you sure you are not hitting this bug by a coincidence: https://github.com/Dasharo/dasharo-issues/issues/295 ?

**Comment by Pokisiekk** [comment] 2023-02-28 14:26
It's hard to judge, I just used F9 in the `Power Management Options` submenu and after reboot I persistently tried to get to the Setup Menu because I had SecureBoot enabled and I couldn't do the internal flash. After about 15 tries to get into the setup menu I was forced to flash externally. If the keyboard in the firmware does not work, I have not had it happen more than 3 times in a row, so I don't think it's related.

**Comment by Pokisiekk** [comment] 2023-03-02 12:17
I reproduced the issue on NV41PZ with v1.5.0 Dasharo firmware

**Comment by miczyg1** [comment] 2023-05-29 08:39
https://github.com/Dasharo/DasharoModulePkg/pull/19

**Comment by miczyg1** [comment] 2023-09-07 08:01
The fix has been release for MSI boards, so removing MSI boards label

**Comment by miczyg1** [comment] 2024-04-16 08:03
The fix definitely is in the latest NovaCustom releases. I guess nobody actually returned here to remove the labels after testing. We can safely close this.

**Comment by miczyg1** [comment] 2024-04-16 08:03
Added back the MSI label so that it will show up in searches as resolved.

**Closed by miczyg1** 2024-04-16 08:03 UTC
Labels: bug, novacustom_ns5x/7x_tgl, novacustom_ns5x/7x_adl, novacustom_nv4x_adl
