### ISSUE TITLE
Unable to login to Windows 11 with the docking station connected

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#357] opened 2023-02-28 14:43 UTC
**Dasharo version**
v1.4.0

**Dasharo variant**
NS51MU, NS70MU

**Affected component(s) or functionality**
Windows login, the docking station

**Brief summary**
Unable to login to Windows 11 with the docking station connected

**How reproducible**
100%

**How to reproduce**

1. Plug in the docking station into Thunderbolt USB-c port.
2. Power on the DUT.
3. Boot into system Windows 11.

**Expected behavior**
The initial screen will be displayed, it is possible to enter the password to log into the system

**Actual behavior**
I have noted two situations:
1. Initial screen starts and nothing can be done, manual reboot required
2. After clicking on the keyboard, it is possible to enter the password, but when entering it, the system freezes and a manual restart is required

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by mkopec** [comment] 2023-04-17 15:16
Seems to work fine for me on Win11 22H2 here, on a NS51MU unit. @Pokisiekk Was there a display connected while the issue appeared?

**Comment by mkopec** [comment] 2023-04-17 15:23
Can't reproduce with a monitor either connected or not connected.

**Comment by mkopec** [comment] 2023-04-18 16:46
The dock seems to have some issues resuming screens from DPMS, when that happens, the external display would stay black and if it was set to primary, then the internal display will remain secondary (black on login screen, unfocused once logged in, appearing "frozen"). @Pokisiekk could this be what you were encountering?

**Comment by mkopec** [comment] 2023-04-19 09:45
https://github.com/Dasharo/coreboot/pull/344 may also help here.

**Comment by Pokisiekk** [comment] 2023-04-20 12:49
@mkopec I don't recall having anything connected to the dock, just when it was connected I couldn't log in as described in the issue. Maybe the system version was to blame because IIRC I tested it on Windows 11 21H2.

**Comment by wessel-novacustom** [comment] 2024-04-15 15:14
Docks have been extensively tested by us and confirmed to be no longer an issue starting from v1.5.2 (TGL) and v1.7.2 (ADL). I believe the issue should be closed, @Pokisiekk.

**Comment by BeataZdunczyk** [comment] 2024-04-24 19:52
We'll check this issue and close it after confirming it's resolved.

**Comment by macpijan** [comment] 2024-06-28 19:15
We have tested these docs countless times during the last release cycle.

**Closed by macpijan** 2024-06-28 19:15 UTC
Labels: bug, novacustom_ns5x/7x_tgl, wavlink WL-UMD0
