### ISSUE TITLE
ISO keyboard issue for non-US layouts NV4xMx

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#259] opened 2022-11-07 12:08 UTC
**Dasharo version**

v1.3.0

**Dasharo variant**

NovaCustom NV4xMx (all platforms probably, but confirmed for NV41MZ-i5)

**Affected component(s) or functionality**

Internal keyboard.

**Brief summary**

When pressing the key right to the left Shift key, the EC triggers the wrong key.

**How reproducible**

100%

**How to reproduce**

1. Make sure you have an ISO keyboard that is set to Belgian.
2. Launch any notepad application under any operating system.
3. Press the key right to the left Shift key. 

**Expected behavior**

The notepad application writes: `<`.

**Actual behavior**

The notepad application writes: `µ`.

**Screenshots**

![ANSI-vs-ISO](https://user-images.githubusercontent.com/100232604/200306121-e698b166-b469-4e57-8a4b-0ebbd14ab3af.png)

https://user-images.githubusercontent.com/100232604/200306701-73badb0d-b534-4c18-b5c4-e872d82d838c.mp4

**Additional context**

This issue happens under Dasharo Tools Suite (DTS, tested with command `loadkeys be`) and Ubuntu as well.
This issue is probably related to the Embedded Controller.
This issue is only applicable for non-US keyboard layouts.

**Solutions you've tried**

None.

**Comment by wessel-novacustom** [comment] 2022-11-07 13:10
As a workaround until this has been solved: most of the keyboard lay-outs have alternative ways to write the characters that are on the affected key.

For example, the keys `<`, `>`, `«` and `»` on an Italian keyboard  can be written with `Shift + Alt Gr + Z`, `Shift + Alt Gr + X`, `Alt Gr + Z` and `Alt Gr + X` respectively. Please check your keyboard settings for a full overview.

Italian example:

![grafik](https://user-images.githubusercontent.com/100232604/200318405-15d5957b-3581-4009-8bc2-db47aa4a9f2c.png)

**Comment by angelocar** [comment] 2022-11-07 14:00
I can confirm that this also happens with my NV41MZ-i7 with the Italian keyboard layout. The temporary workaround works well though.

**Comment by mkopec** [comment] 2022-11-07 14:18
I can confirm this is a bug in the firmware. We hadn't noticed it in testing since on all our units with ISO keyboards, the [highlighted keys](https://user-images.githubusercontent.com/100232604/200306121-e698b166-b469-4e57-8a4b-0ebbd14ab3af.png) have the same symbols on them. Looks like we have to handle ISO layouts in the EC firmware in a smarter way.

**Comment by wessel-novacustom** [comment] 2022-11-07 14:27
I will send you a German keyboard @mkopec

**Comment by MasterBootRecord-KML** [comment] 2022-11-08 13:50
As we've discussed with @wessel-novacustom by mail, this issue happened on my computer with AZERTY fr and AZERTY be on Arch Linux and on Mageia using GNOME Desktop Environment as well as in shell command line in Dasharo Tools Suite v1.1.0. 

**My hardware :** NV40MZ with Intel i7-1165G7 and Intel Xe Graphics ;
**Dasharo version :** v1.3.0

I have seen no workaround for these keys at the moment but if I found a solution I will post it here.

You can see the problem using the french keyboard on the video below.
--First clicks, typing on the "< >" and second clicks, typing on the "* µ" :
[Capture vidéo du 2022-11-03 18-54-35.webm](https://user-images.githubusercontent.com/117741516/200578811-8a8b2ee2-3b4b-44f0-8941-910905aeb841.webm)

**Comment by Appliumus** [comment] 2022-11-09 12:11
I have the same issue with my NV40MZ with Intel i7-1165G7 and Intel Xe Graphics and German Keyboard Layout.

**Comment by wessel-novacustom** [comment] 2022-11-15 07:11
Great to know! That will be in several weeks, I suppose, as we will arrange fix releases.

If customers did not choose to get firmware update notifications, they can sign up for this by contacting us directly.

This should be possible via the release notes of the customer's model via [this page](https://docs.dasharo.com/unified/novacustom/overview/), too.

However, these pages seem to be under construction at this time.

I will close the issue once the update has been released.

**Comment by PrzemyslawBanasiak13** [comment] 2022-11-17 14:18
On NV41PZ with Dasharo v1.4.0 firmware and EC firmware, the key shown on the video in the **Screenshots** section (the `>`/`<` key) works properly. Tested on **Windows 11** with `Belgian (Comma)` and `English (United States)` keyboard layouts and on **Ubuntu 22.04** Dutch (`Belgian`, `Belgian(ISO, alt.)`, `Belgian(Wang 724 AZERTY)` ) and `English (US)`.

**Comment by mkopec** [comment] 2022-11-17 14:23
Thanks, same change will apply to the next release for NV4xMx (Tiger Lake), so let's keep this issue open until it's released.

**Comment by Pokisiekk** [comment] 2023-02-24 11:07
I confirm this works fine on the NV41MZ so I'm closing the issue

**Closed by Pokisiekk** 2023-02-24 11:07 UTC
Labels: bug, novacustom_nv4x_tgl
