### ISSUE TITLE
HCL report for V560TNE does not contain info about audio

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1017] opened 2024-08-22 05:28 UTC
### Component

Dasharo Tools Suite

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc3

### Brief summary

HCL report for V560TNE does not contain info about audio needed for AUD tests

### How reproducible

It is a fact

### How to reproduce

Try to find it in the HCL report

### Expected behavior

Should contain it

### Actual behavior

does not

**Comment by BeataZdunczyk** [comment] 2024-08-23 10:17
This is related to https://github.com/Dasharo/dasharo-issues/issues/247. It’s not clear for me if this is a duplicate. The issue is already in progress of being fixed for ADL. We should test whether this fix resolves the situation for MTL before merging, @artur-rs.

**Comment by philipandag** [comment] 2024-09-16 06:56
I have created a HCL report on V540TND on v0.9.1-rc5. "Sound card files are missing!" And multiple errors
![20240916_084004](https://github.com/user-attachments/assets/9749a392-4d1c-4113-8dcf-66471a44e7c1)

**Comment by mkopec** [comment] 2024-09-17 15:09
Duplicate of https://github.com/Dasharo/dasharo-issues/issues/247

**Closed by mkopec** 2024-09-17 15:09 UTC
Labels: bug, DasharoToolsSuite, needs review, novacustom_v56_mtl
