### ISSUE TITLE
Can't enable Intel ME v0.9.1-rc3 V560TND

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1027] opened 2024-08-23 13:52 UTC
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc3

### Dasharo Tools Suite version

--

### Test case ID

MNE002.001

### Brief summary

ME is disabled despite being enabled in Setup

### How reproducible

100% now

### How to reproduce

Set `Intel ME mode` to `Enabled`. check if it is working. I tried these commands:
- lspci | grep 00:16.0
- lspci | grep -i management
- intelmetool --me

### Expected behavior

with lspci the ME engine entry should be found, like: "Intel Corporation Meteor Lake Management Engine Interface"
with intelmetool info about ME should be printed

### Actual behavior

"lspci | grep " commands find nothing
coreboot intelmetool says `Can't find ME PCI device`

### Additional context

I have first disabled the ME (soft) and only then checked if `Enabled` works which is not the default order of the tests. I don't know if it worked initially.

### Solutions you've tried

rebooting, diabling and reenabling

**Comment by mkopec** [comment] 2024-08-23 13:53
I believe this is a duplicate of https://github.com/Dasharo/dasharo-issues/issues/984

**Comment by philipandag** [comment] 2024-09-12 06:53
On V540TND v0.9.1-rc5 the ME is visible in `lspci` as `00:16.0 Communication controller: Intel Corporation Device 7e70 (rev 20)` which is probably an issue with the OS not defining a name for this device ID. `intelmetool` says `Can't find ME PCI device` which may be related to the naming issue. @mkopec should this be considered fixed?

**Closed** 2024-09-12 09:30 UTC
Labels: bug, firmware, needs review, novacustom_v56_mtl
