### ISSUE TITLE
Laptops randomly go into suspend mode from which they can not wake up.

### ISSUE THREAD

**Issue by johanes2115** [Dasharo/dasharo-issues#474] opened 2023-08-09 10:23 UTC
**Firmware**
2023-06-29_0428312 EC firmware

**Dasharo variant**
nv41pz, nv41mz, ns70pu, ns70mu

**Affected component(s) or functionality**
Suspend and sleep

**Brief summary**
Laptops when powered on and sitting still, randomly go into suspend mode from which they can't wake up. The fan spins, but the screen is blank and the laptop does not react to keyboard and power button presses. The only way to make it work is to unplug and then plug back in the battery.

**How reproducible**
Leave the laptop sitting while powered on and wait. The bug can happen in a random amount of time - sometimes 5 minutes, sometimes an hour.

**Comment by miczyg1** [comment] 2023-08-10 07:57
@johanes2115 are they configured for S3 suspend or S0ix?

**Comment by johanes2115** [comment] 2023-08-16 11:55
@miczyg1 S0ix

**Comment by miczyg1** [comment] 2023-09-11 14:41
https://github.com/Dasharo/ec/pull/45
https://github.com/Dasharo/coreboot/pull/390

**Comment by mkopec** [comment] 2023-09-28 11:18
@johanes2115 can we confirm this issue is fixed in the new release?

**Comment by macpijan** [comment] 2023-11-12 15:25
We have had no reports since then, but let's double check this week that this problem does not happen anymore.

**Comment by wessel-novacustom** [comment] 2023-11-15 10:43
@johanes2115 Did it happen on Ubuntu, Fedora, Windows? Or maybe all OSses?

You indicate it might happen after only 5 minutes or after an hour. Can this be related to the OS setting/policy of going into sleep mode after x minutes of inactivity?

I haven't been able to reproduce it yet on the latest test binaries I got, but I must say I did extensive testing which is probably not the way to trigger the problem.

**Comment by mkopec** [comment] 2023-11-16 11:53
We have not been able to reproduce this issue on the latest code.

**Closed by mkopec** 2023-11-16 11:53 UTC
Labels: bug, novacustom_nv4x_tgl, novacustom_ns5x/7x_tgl, novacustom_ns5x/7x_adl, novacustom_nv4x_adl
