### ISSUE TITLE
Warning sign in device manager under the touchpad device

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dasharo-issues#194] opened 2022-09-13 08:48 UTC
**Dasharo version**

v1.3.0

**Dasharo variant**

NS70MU

**Affected component(s) or functionality**

Probably some parts of Dasharo firmware

**Brief summary**

Warning sign appears in Device Manager on Windows 11 under the touchpad device

**How reproducible**

100%

**How to reproduce**

1. Boot Windows 11
2. Enter Device Manager

**Expected behavior**

There are no warnings or errors reported in the Device Manager, which is
very concerning for end users.

**Actual behavior**

There is a warning next to the touchpad device

**Screenshots**

**Additional context**

Maybe it's related to the missing drivers of some kind. In such a case,
we should at  least improve documentation in that regard.

**Solutions you've tried**

**Comment by wessel-novacustom** [comment] 2022-09-29 07:57
I can confirm that this is only applicable for NS70MU platform and not for NS51MU.

**Comment by johanes2115** [comment] 2023-07-25 13:36
The issue does not occur on NS70MU with Dasharo v1.4.0 firmware.

**Comment by wessel-novacustom** [comment] 2024-04-15 14:22
The issue is no longer present and needs to be closed.

**Comment by BeataZdunczyk** [comment] 2024-04-24 20:12
Fixed in a [v1.5.1 firmware](https://docs.dasharo.com/variants/novacustom_ns5x_tgl/releases/#v151-2023-11-06), so I'm closing this issue.

**Closed by BeataZdunczyk** 2024-04-24 20:12 UTC
Labels: bug, novacustom_ns7x_tgl
