### ISSUE TITLE
Press F2 to enter setup sometimes doesn't work

### ISSUE THREAD

**Issue by MasterBootRecord-KML** [Dasharo/dasharo-issues#400] opened 2023-04-02 10:50 UTC
**Dasharo version**
v1.4.0

**Dasharo variant**
 NovaCustom NV40MZ (Tiger Lake variant) running GNOME and Arch Linux.

**Affected component(s) or functionality**
F2 function key.

**Brief summary**
When the F2 key is pressed, when the UEFI splash screen is displayed, the computer don't enter the UEFI setup.

**How reproducible**
Seems to appear everytime the computer reboots and sometimes when the device cold boot when plugged to power. The issue is also random when unplugged from power, when cold booting.

**How to reproduce**
Steps to reproduce the behavior :

On reboot : 
1. Reboot the computer from the O.S. ;
2. Wait till the reboot procedure ends and press F2 key ;
3. The UEFI splash screen is displayed and the computer continues to boot normally.

On cold boot : 
1. Shutdown the computer ;
2. Press the power on key ;
3. Press F2 key and at that point, two solutions : 
- The computer boots up normally ;
- The computer displays the UEFI setup.

**Expected behavior**
When the computer starts up, when the F2 function key is pressed, the UEFI setup should be displayed.

**Actual behavior**
When the computer reboots, even when the F2 key is pressed, the computer continues to boot normally. When the computer cold boots and when the F2 key is pressed, the computer displays the UEFI setup but sometimes, it does not (see attached videos).

**Videos**
Failed to enter UEFI setup on reboot :
https://user-images.githubusercontent.com/117741516/229348065-762f19c7-3cd5-448b-9784-d2e999a5eebd.mp4

Failed to enter UEFI setup on cold boot : 
https://user-images.githubusercontent.com/117741516/229348088-2468b113-c49b-489f-9033-c024f0be7c86.mp4

Succeed to enter UEFI setup on cold boot (by unplugging the power cord) :
https://user-images.githubusercontent.com/117741516/229348183-aa7f76c4-bae7-42eb-9947-1c3c8d757b59.mp4

**Additional context**
None.

**Solutions you've tried**
Enable / disable the function lock feature by pressing "Fn" + "Caps lock" : does not solve the issue.
Unplug the computer from the power source : seems to fix the issue sometimes but not sure if it is related.

**Comment by macpijan** [comment] 2023-04-03 07:49
Thanks for a detaield report!

I believe that it is a duplicate of: https://github.com/Dasharo/dasharo-issues/issues/295

What might be interesting is that we got to the bottom of this problem for the upcoming 12th Gen (Alder Lake) releases. It is likely that we will be able to replicate the same fixes for 11th Gen (Tiger Lake) future releases as well.

**Closed by macpijan** 2023-04-03 07:49 UTC
