### ISSUE TITLE
Sleep sometimes not working

### ISSUE THREAD

**Issue by thePretendend** [Dasharo/dasharo-issues#261] opened 2022-11-08 20:54 UTC
**Dasharo version**

v1.4.0

**Dasharo variant**

NS5x_NS7xPU

**Affected component(s) or functionality**

Sleep / Suspend

**Brief summary**

When closing the laptop lid, the laptop (NovaCustom NS51PU with intel Alderlake does not suspend. When suspending via Alt+F12, the system sometimes immediately wakes up again (dmesg shows no errors, only that the system immediately wakes up after suspending) and sometimes it takes up to 3 tries until the system stays suspended. Powerindicater only starts to blink when system is suspended via key combo, AND lid is closed.

**How reproducible**

Occasionaly

**How to reproduce**

1. Press Alt+F12
2. Try again
3. OR only close the lid

**Expected behavior**

System suspends and stays suspended when closing the lid, and only wakes up when opening the lid

**Actual behavior**

System does not suspend at all when closing the lid (but turns of keyboard light and display) and sometimes takes up to 3 tries to suspend via Alt+F12

**Screenshots**

**Additional context**

OS: Fedora 37 Silverblue
Kernel: Linux 6.0.7-301.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 4 18:35:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Wifi module: Intel Wi-Fi 6 AX200 rev 1a

**Solutions you've tried**

There are none. It's a bug.

**Comment by thePretendend** [comment] 2022-11-09 15:45
I have noticed there is a similar issue, but it definitely is not the same, since when I for example just close the lid (and wait) the cooling fan stays on, indicating the system does not suspend.

**Comment by thePretendend** [comment] 2022-11-13 16:10
Today I have done a bit of testing and I believe the actual issue may be the intel driver for the network card (iwlmvm). Unloading it lets the system suspend and stay suspended. The issue with the system not suspending when closing the lid still persists.

**Comment by wessel-novacustom** [comment] 2022-11-16 10:15
I believe @macpijan has told me that it can be related to the Intel Wireless card, indeed. That being said, this should be fixed with a firmware update.

**Comment by PrzemyslawBanasiak13** [comment] 2022-11-17 17:07
Couldn't reproduce this bug on NS70PU with Dasharo 1.4.0. It looks like it may work fine now. Tested on Fedora 37, 38 (Unstable), and Ubuntu 22.04

**Comment by wessel-novacustom** [comment] 2022-11-17 17:09
@PrzemyslawBanasiak13 it looks like some configurations are affected, while some are not.

We will have to wait for feedback of the firmware developer's team on this subject.

**Comment by macpijan** [comment] 2022-11-17 19:30
@PrzemyslawBanasiak13 

> Couldn't reproduce this bug on NS70PU with Dasharo 1.4.0

But the 1.4.0 for NS50/70 does not contain the suspend improvements we have just included for the NV4X release, so I'm wondering why it's been improved :thinking: 
Are you sure it is released 1.4.0 version, or maybe some test build?

**Comment by PrzemyslawBanasiak13** [comment] 2022-11-18 09:21
Tested on NV41PZ with Dasharo 1.4.0 on Fedora 37 and 38 (pre-release), and the bug doesn't seem to occur in this setup also

@macpijan 

> Are you sure it is released 1.4.0 version, or maybe some test build?

Probably it was a test build, so to test it again I've flashed the NS51PU with the latest Dasharo (1.4.0), and sleep mode on Fedora 37 and 38 seems to work fine. When the lid is closed or the `Fn+F12` key combination is pressed, the device turns to sleep mode

**Comment by wessel-novacustom** [comment] 2024-04-15 14:39
@thePretendend The issue no longer seems to happen since the latest releases. Could you close the issue, please?

**Closed** 2024-04-21 02:41 UTC
Labels: bug, novacustom_ns5x/7x_adl
