### ISSUE TITLE
DTS allow deployment on Z690 with 13th Gen CPU, despite 13th Gen is not supported

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#440] opened 2023-05-11 19:26 UTC
> Huh, there is nothing about not using dasharo on 13th gen, only a notice about ddr5 version a d coreboot mainline not supporting 13th gen. Either this or im didn't rtfmed enough.

Consider adding a simple bash script to waern dumbasses like me to not proceed if /dev/cpuinfo contains "13th" :-)

Damn, so ch341a for me...

_Originally posted by @inoperable in https://github.com/Dasharo/dasharo-issues/issues/439#issuecomment-1543483459_

**Comment by WiktorG351** [comment] 2024-03-21 15:46
@artur-rs support for 13th gen CPU's has been added in [DTS v1.2.7](https://github.com/Dasharo/meta-dts/blob/main/CHANGELOG.md#v127---2023-09-05) and in [Dasharo v1.1.2](https://docs.dasharo.com/variants/msi_z690/releases/#v112-2023-09-06) for the Z690, so this issue can be closed.

**Comment by artur-rs** [comment] 2024-03-21 15:55
@WiktorG351 thanks. 

The feature request for a warning before flashing unsupported hardware can return in the future. @TomaszAIR @WiktorG351 Do we already have such a mechanism in DTS?

**Comment by WiktorG351** [comment] 2024-03-21 16:04
@artur-rs we have something similar, but not quite what you are asking about [here](https://github.com/Dasharo/meta-dts/blob/main/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy#L78-L94). 

We ask the user to verify whether they actually want to flash the detected hardware, but determining whether it is supported is up to the user, who has to look up that information.

**Comment by artur-rs** [comment] 2024-03-21 16:36
Ok, it is sufficient for now. If required, we can raise a new feature request.

**Comment by miczyg1** [comment] 2024-03-22 10:36
@artur-rs @WiktorG351 you completely missed the point here...

The problem is that users without DES subscription choosing a deployment will be flashed with v1.1.1 version, which does not support 13th gen CPU! IT will cause them a bricked platform without an option for recovery (FLashBIOS is not supported on v1.1.1 yet). This is what this issue was supposed to address.

What we need to check is the presence of 13th and 14th gen CPU and DTS should not attempt to flash Dasharo v1.1.1 on it.

**Comment by WiktorG351** [comment] 2024-03-25 12:33
@miczyg1 I understand now, thanks for the explanation. Do You think something like [this](https://github.com/Dasharo/meta-dts/pull/108) works?

**Comment by zirblazer** [comment] 2024-03-25 20:32
Note that it is a bit convoluted to do a catch-all Processor detection. CPUID for Family / Model / Stepping is not reliable because there are 13th and 14th gen parts using the same values, and it was never tested if old Alder Lake FSP (From Dasharo 1.1.1) can POST with rebranded 13th and 14th gen parts (Like a 14100, which is based on the H0 Alder Lake 6P/0E die). They may also require a newer ME version anyways.
Most likely you want some kind of parser that checks if Processor Name begins with i3-12/i5-12/i7-12/i9-12 plus individual exceptions for Celeron G6900 and Pentium G7400. [Here is Intel Ark list of Alder Lake](https://ark.intel.com/content/www/us/en/ark/products/codename/147470/products-formerly-alder-lake.html#@Desktop).

**Comment by miczyg1** [comment] 2024-03-26 08:15
@zirblazer we simply check for the `-13XXX` and `-14xxx` pattern in the brand string. Raptor Lake does not have any Celerons and Pentiums, so it is easier with negative logic.

**Comment by miczyg1** [comment] 2024-03-26 08:15
https://github.com/Dasharo/meta-dts/pull/108 merged, closing.

**Closed by miczyg1** 2024-03-26 08:15 UTC
Labels: DasharoToolsSuite
