### ISSUE TITLE
The screen brightness level gets stuck when key are held or pressed too fast

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#341] opened 2023-02-20 09:09 UTC
**Dasharo version**
v1.4.0

**Dasharo variant**
NS70MU, NS51MU, NV41MB, NV41MZ

**Affected component(s) or functionality**
The function keys to change the brightness of the screen (`Fn` + `F8` and `Fn` + `F9`).

**Brief summary**
The function keys to change the brightness of the screen do not work properly.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot into Windows 11.
3. Press or hold `Fn` + `F8` and `Fn` + `F9` in different configuration.

**Expected behavior**
Pressing the `Fn` + `F8` should decrease the brightness of the internal LCD display.
Pressing the `Fn` + `F9` should increase the brightness of the internal LCD display.
Each key press should cause a brightness down notification to appear in the top left of the screen.

**Actual behavior**
Holding or fast pressing the function keys sometimes leads to an increase the brightness when pressing `Fn` + `F8` or a decrease the brightness when pressing `Fn` + `F9` (usually one iteration when changing from highest brightness to lowest)
Holding the `Fn` + `F9` stops at the level shown on the image below:

![Screenshot from 2023-02-20 10-02-43](https://user-images.githubusercontent.com/101700648/220060502-55f0ec01-95cf-4168-9a27-07d7b6645b61.png)

To make the screen as bright as possible in this situation, lower the brightness and increase it again.

Using the function keys to change the brightness at some point is no longer possible, at the level shown in the picture below:

![Screenshot from 2023-02-20 10-02-10](https://user-images.githubusercontent.com/101700648/220060439-0598496c-2a3f-4827-a80e-83ab22626a5a.png)

Restarting the system does not help, manual brightness change in the settings is required to unblock the function keys.

**Additional context**
Windows 11 21H2

**Comment by macpijan** [comment] 2023-02-24 15:57
`NV40MB 1` v1.4.0. Cannot reproduce the problem.

**Comment by mkopec** [comment] 2023-02-24 16:14
Seems to happen on Win11 21H2 but not on 22H2.

**Comment by macpijan** [comment] 2023-02-24 16:21
Updated the title to be more accurate - originally it indicated that the keys do not work at all, which was not true.

**Comment by wessel-novacustom** [comment] 2024-04-15 15:01
@Pokisiekk It seems like the issue is no longer present. Could you close the issue, please?

**Comment by PLangowski** [comment] 2024-05-06 10:55
Tested on: NV41MZ, Dasharo `v1.5.2`, Windows 22H2. The issue does not occur.

**Comment by PLangowski** [comment] 2024-05-07 11:56
I'm attaching a gif, which shows the brightness bar moving without any issues After holding/rapidly pressing `Fn+F8` and `Fn+F9`.

![brightness](https://github.com/Dasharo/dasharo-issues/assets/105967771/ffbd1320-99b4-49cd-9685-a45f9a7f4f82)

**Closed by PLangowski** 2024-05-07 11:56 UTC
Labels: bug, novacustom_nv4x_tgl, novacustom_ns5x/7x_tgl
