### ISSUE TITLE
Display brightness not dark enough

### ISSUE THREAD

**Issue by fischtoeter** [Dasharo/dasharo-issues#297] opened 2022-12-21 20:35 UTC
**The problem you're addressing (if any)**
Sitting in a dark room, the display brightness is not dark enough. Usually the brightness is decreasable till display turns off.

**Describe the solution you'd like**
Using FN+F8 to decrease display brightness till display is almost completely dark.

**Where is the value to a user, and who might that user be?**
Laptop is usable in rooms with low ambient light - like its possible with any laptop available.

**Describe alternatives you've considered**
Using an addon in the browser to change white colour to black. But this doesnt work for pictures or any other program.

**Comment by miczyg1** [comment] 2023-01-11 14:34
@fischtoeter we also need the device model and firmware version to help you

**Comment by macpijan** [comment] 2023-04-12 07:08
@miczyg1 @mkopec Can minimum display brightness level on NV4X ADL be set to even lower than it is right now?
Where is it configured in code?

**Comment by mkopec** [comment] 2023-04-12 08:55
Looks like the backlight can go one step lower if you run `echo 0 | sudo tee /sys/class/backlight/acpi_video0/brightness`. The levels are defined here: https://github.com/Dasharo/coreboot/blob/clevo/release/src/mainboard/clevo/adl-p/acpi/backlight.asl

It's also interesting that Linux chooses to use acpi_video instead of Intel native backlight driver which provides smoother steps. Worth a look to see what can be done.

**Comment by miczyg1** [comment] 2023-04-12 09:51
Brigthness levels are defined here: https://github.com/Dasharo/coreboot/blob/clevo/release/src/mainboard/clevo/adl-p/acpi/backlight.asl#L10
We can define as much steps as we want.

**Comment by macpijan** [comment] 2023-04-12 10:25
So it seems we have defined 20 levels, but the lowest one (level 0 - 5%) is not reachable via hotkeys.
Allowing it to be reachable via hotkey would improve the situation already, IMHO, and possible also resolve the issue originally reported by @fischtoeter

**Comment by wessel-novacustom** [comment] 2024-04-15 14:50
@macpijan Is it possible to solve this for a next NovaCustom Dasharo firmware release?

**Comment by mkopec** [comment] 2024-04-24 09:24
There's also some `Minimum brightness` fields in VBT, may be relevant here too.

**Comment by filipleple** [comment] 2024-06-07 13:28
Fixed by https://github.com/Dasharo/coreboot/pull/515 - lowered the minimum brightness level achievable via hotkeys.

**Closed** 2024-06-07 13:38 UTC

**Comment by macpijan** [comment] 2025-09-26 08:01
Let's confirm if this is included for the upcoming ADL relase.

**Comment by philipanda** [comment] 2026-03-10 08:41
The minimum reachable brightness using hotkeys adjustment is still visible on v1.8.0-rc8.
The minimum brightness is visibly darker on NV41PZ Dasharo v1.8.0-rc8 (left) compared to Dasharo v0.9.0 (right).

<img width="1920" height="1440" alt="Image" src="https://github.com/user-attachments/assets/0cfee19b-6bcc-4545-a504-9696cc68c2d4" />

Whether the issue is fully solved might be debatable:
>  Usually the brightness is decreasable till display turns off.
