### ISSUE TITLE
Make it possible to associate the HCL report with a given device and present what is in it

### ISSUE THREAD

**Issue by TomaszAIR** [Dasharo/dasharo-issues#220] opened 2022-10-11 07:25 UTC
**The problem you're addressing (if any)**

The HCL report created by DTS should connect somehow the report with the name of the device on which te report was generated (e.g. serial number?). Also after dumping info we could print on screen what is inside HCL report.  Maybe a table with information what is inside the package like BIOS backup, information about PCI, EC, SMBIOS, ACPI tables etc.

**Describe the solution you'd like**

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Comment by kotylamichal** [comment] 2022-10-17 16:13
@TomaszAIR not on all of the machines serial number field is filled. Example from my PC:

```
# dmidecode 3.4

[...]

        Serial Number: To be filled by O.E.M.
        UUID: [...]
        Wake-up Type: Power Switch
        SKU Number: To be filled by O.E.M.
        Family: To be filled by O.E.M.

Handle 0x000C, DMI type 12, 5 bytes
System Configuration Options
        Option 1: To be filled by O.E.M.
```

but there is UUID so my proposition is to use combination UUID+serial, for example:

`aaaa-bbbb-cccc-ddde-eeee+123456789`

or just only UUID if serial was not filled

**Comment by esesyn01** [comment] 2022-10-21 08:15
@TomaszAIR Sadly, also UUID isn't always set:
```
# dmidecode -s system-uuid
Not Settable
```
Combining both UUID and Serial number might work, but there are also problems:
- We cannot guarantee that even one of them will be set. If the field is empty, we shouldn't add it to the name, so if both of them weren't set, we should not add anything.
- Also, it is hard to determine if the serial number is set. In UUID, there is a format so that it won't be challenging, but the serial number is pretty undefined. The output of dmidecode in such cases also can vary. It can be blank or a different message, like `To be filled by O.E.M.` in the above comment. So, how can we determine if the serial number is set?

**Comment by esesyn01** [comment] 2022-10-21 08:26
@TomaszAIR There is also an option to combine even more information, like MAC address UUID, serial number, etc., and hash it with sha256, for example. Then, at the end of the report's script, we will display this generated hash or even the whole filename, consisting only of `product-name-hash-date.`

**Comment by esesyn01** [comment] 2022-10-21 09:11
@TomaszAIR At the end of the report, we should display only information what exactly is being sent, not the values of the sent things right?

**Comment by macpijan** [comment] 2022-10-21 09:59
We cannot rely on SMBIOS data for it. We need to assign our own identification number for this, I'm afraid.

**Comment by esesyn01** [comment] 2022-10-21 10:53
@macpijan So, the idea to hash MAC address, UUID, and so on doesn't meet the requirements for that new ID? How can we provide our own identification number instead? We would need to assure that the ID will be unique, so either we will have a great generation process that won't allow replies or store all the IDs and compare them all to avoid duplicates. Such an ID has to be integrated with Yocto build and hidden in the system.

**Comment by macpijan** [comment] 2022-10-21 11:02
If every person on the planet generates a new UUID4 every second, we’d expect a collision to occur after about 10 years.
Or something like that.

**Comment by esesyn01** [comment] 2022-10-21 11:06
Yes, but UUID, as I mentioned before, is not always set

**Comment by macpijan** [comment] 2022-10-21 11:15
> So, the idea to hash MAC address, UUID, and so on doesn't meet the requirements for that new ID?

It might work.

You might also take a look on how fuwupd generates GUIDs: https://github.com/fwupd/fwupd/tree/main/plugins/flashrom#guid-generation


```
fwupdtool hwids
Computer Information
--------------------
BiosVendor: coreboot
BiosVersion: Dasharo King's Gambit v0.2
Manufacturer: Dell Inc.
Family: 
ProductName: OptiPlex 9010
ProductSku: 
EnclosureKind: 3
BaseboardManufacturer: Dell Inc.
BaseboardProduct: OptiPlex 9010

Hardware IDs
------------
not available as 'BiosMajorRelease' unknown
not available as 'BiosMajorRelease' unknown
not available as 'BiosMajorRelease' unknown
{9b80d899-1bc3-54d2-9ff0-5fe186f34157}   <- Manufacturer + Family + ProductName + ProductSku + BaseboardManufacturer + BaseboardProduct
{10f903f5-58f7-568b-9822-dfda3d71b371}   <- Manufacturer + Family + ProductName + ProductSku
{3fb4d6ce-d747-58a3-985f-d74e97b8c3d7}   <- Manufacturer + Family + ProductName
{67f94af9-7e51-59bd-94c6-9cbfd8fa1dff}   <- Manufacturer + ProductSku + BaseboardManufacturer + BaseboardProduct
{c5c87080-5af3-53f9-bcd4-35577b7397f8}   <- Manufacturer + ProductSku
{03b4ebd8-c627-546c-8aa7-8a4af56be12b}   <- Manufacturer + ProductName + BaseboardManufacturer + BaseboardProduct
{8fa56a7c-89da-5a82-9e55-548b5006efd7}   <- Manufacturer + ProductName
{67f94af9-7e51-59bd-94c6-9cbfd8fa1dff}   <- Manufacturer + Family + BaseboardManufacturer + BaseboardProduct
{c5c87080-5af3-53f9-bcd4-35577b7397f8}   <- Manufacturer + Family
{529aea4b-4247-5705-89e2-edc2edd08c4e}   <- Manufacturer + EnclosureKind
{f54d7b22-f032-56f0-8360-de23fcf36ae2}   <- Manufacturer + BaseboardManufacturer + BaseboardProduct
{85d38fda-fc0e-5c6f-808f-076984ae7978}   <- Manufacturer
```

These are rather not specific to a single device, but to a group of devices, but we may extend this idea also, for example.

> We would need to assure that the ID will be unique, so either we will have a great generation process that won't allow replies or store all the IDs and compare them all to avoid duplicates. Such an ID has to be integrated with Yocto build and hidden in the system.

"If every person on the planet generates a new UUID4 every second, we’d expect a collision to occur after about 10 years."
Or somehting like that.
So if we would generate our own, we do not need to worry about that.

**Comment by macpijan** [comment] 2022-10-21 11:25
This is how these are generated: https://lvfs.readthedocs.io/en/latest/metainfo.html?highlight=guid#using-guids
So we could for example use similar apporach (so we do not invent our own from scratch), by reusing one of these (e.g. ` Manufacturer + Family + ProductName + ProductSku + BaseboardManufacturer + BaseboardProduct`  but extending the input sctring with some device-specific information, like MAC address)

**Comment by esesyn01** [comment] 2022-10-21 12:07
@macpijan How can we assign such generated UUID to hardware? Can't we just store the information in a file on a disk?

**Comment by macpijan** [comment] 2022-10-21 14:58
> How can we assign such generated UUID to hardware? 

We probably cannot in a reliable way. The only way would be to save somewhere in SPI flash where firmware resides. But when we change firmware, it's lost.

That makes the idea of generating the UUID based on hardware information the only viable one, I suppose.


> Can't we just store the information in a file on a disk?

No, that would be totally unreliable.

**Comment by esesyn01** [comment] 2022-10-24 08:25
@macpijan @TomaszAIR Saving in SPI flash seems reasonable. Even if it is lost after changing firmware, it can be recreated. Basing the UUID generation on a non-random or easy-to-change string (like concatenating MAC address, manufacturer, product name, etc.) allows receiving the same output. The problem is when someone has a report from Dasharo firmware, and the person changes to another firmware. Then, the UUID won't be helpful.

**Comment by pietrushnic** [comment] 2022-10-24 11:38
@esesyn01 this is from newsletter related to Dasharo Subscription:

> Due to necessary changes to the board, MSI’s standard warranty does not apply to this product.
3mdeb guarantees the proper operation of the platform for two years under the following conditions:
> 1. Hardware used only the Certified Dasharo firmware version. If other firmware is or was installed, the warranty is void.
> 2. No signs of customer interference with the platform or firmware.
> 3. A customer delivers a 3mdeb platform at their own expense for analysis and possible repair, together with a detailed description of a problem.

> When all the above conditions are met, 3mdeb will try to restore the original configuration and re-flash Dasharo.
3mdeb will send the platform back to the client at 3mdeb's expense, provided that the client has not breached the provisions of conditions 1 and 2.
> In the event of failure to meet the above conditions or culpable action of the customer, the warranty repair is not entitled, and the warranty for a given item is canceled.

Does it help?

**Comment by macpijan** [comment] 2022-10-24 11:50
MAC is easy to change by user from OS, too. But we can assume we will not do this when running HCL just to break stuff.
I think we can start with generating UUID based on strings from SMBIOS + MAC. We can also save it in the SPI when we deploy Dasharo using DTS.

> The problem is when someone has a report from Dasharo firmware, and the person changes to another firmware. Then, the UUID won't be helpful.

We should try to propose such insut strings that would not change, even when we change firmware from proprietary to Dasharo.
Please note that we retain such strings in Dasharo: https://docs.dasharo.com/dev-proc/smbios-rules/#system-information-type-1
We only change the `BIOS version` and `BIOS vendor` fields.

**Comment by esesyn01** [comment] 2022-10-26 12:19
Here is my proposition for the UUID implementation: https://github.com/Dasharo/meta-dts-ce/pull/9.
I have chosen the device's MAC address, system manufacturer, and product name. Then, the report's name consists of the system product name, generated UUID, and date.

I don't know if it is a good place for generating this UUID in the HCl report. We should generate it once, perfectly when flashing Dasharo, but we can offer this only on Dasharo. When another firmware will be installed, the best solution will be to generate it directly in the report creation procedure.

For now, I will keep it there, and in the future, when the UUID will be saved when deploying Dasharo, this can be changed to seek for the UUID first, then, when empty, generate it.

**Comment by kotylamichal** [comment] 2022-10-27 08:58
Filename on stock fw: `NS50_70MU_ea8c500d-10d1-5ebe-8775-cc699101e379_2022_10_27_08_45_54_895901807.tar.gz`
Filename on dasharo fw: `NS50_70MU_ea8c500d-10d1-5ebe-8775-cc699101e379_2022_10_27_08_57_13_903544744.tar.gz

@TomaszAIR so it is the same UUID: `ea8c500d-10d1-5ebe-8775-cc699101e379`

**Closed** 2022-10-30 05:59 UTC
Labels: DasharoToolsSuite
