### ISSUE TITLE
Migrate coreboot TPM event log entries to UEFI payload

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#278] opened 2022-12-05 10:14 UTC
**Dasharo version**
Any

**Dasharo variant**
Any

**Affected component(s) or functionality**
TPM event log

**Brief summary**
Currently, the coreboot event log entries are not propagated to the UEFI payload so all information what was measured to PCRs is lost when EDK2 TPM drivers kick in. This results in the inconsistent TPM event log with PCRs being returned from UEIF to OS.

**How reproducible**1
100%

**How to reproduce**

1. Use tpm2 tools event log utility to calculate final PCRs values and compare them to PCR values taken from TPM.

**Expected behavior**
Calculated PCR values are identical to those read from TPM.

**Actual behavior**
Calculated PCR values are not identical to those read from TPM.

**Screenshots**
None

**Additional context**
None

**Solutions you've tried**
None

**Comment by macpijan** [comment] 2024-06-28 19:01
Seems to be a duplicate of: https://github.com/Dasharo/dasharo-issues/issues/455 - which provides more context and discussion already.

**Closed by macpijan** 2024-06-28 19:01 UTC
