### ISSUE TITLE
Raptor Lake S support

### ISSUE THREAD

**Issue by miczyg1** [Dasharo/dasharo-issues#130] opened 2022-06-08 14:14 UTC
**The problem you're addressing (if any)**
Lack of Raptor Lake S CPU support in coreboot

**Describe the solution you'd like**
Enable support for Raptor Lake S CPUs in coreboot for Dashar compatible with MSI PRO Z690-A DDR4

**Where is the value to a user, and who might that user be?**
Users migrating to newer CPUs.

**Describe alternatives you've considered**
None

**Additional context**
None

Edit: 14.06.2023

Added scope (from NLnet application) that will be covered in the next release:

Dasharo Compatibility: MSI PRO Z790-P support in coreboot
Once CPU and chipset bringup is implemented, the next step will be to add a board build target to coreboot and initial release of Dasharo for testing. The effort also includes integration of the board into 3mdeb testing lab, enabling automated testing framework for the new board and providing automated builds with testing through CI/CD.

**Comment by zirblazer** [comment] 2022-10-11 15:18
Raptor Lake-S is supposed to launch on 20 October, along with 700 series Chipsets and Motherboards using them. The cheapest Processor model available on launch is the 13600K with the lower models coming up later, thus depending on price, it may leave obsolete all the Alder Lake-S lineup above the 12400. As such, support for Raptor Lake as soon as possible is a must, albeit I suppose the bottleneck will be Intel releasing FSP.
And the MSI Z690 has a bit more than a week to go as current/latest generation before being replaced by a slighty newer Z790 version. You likely want to do both new Processor + new Motherboard support because new builders will want to use latest Hardware.

**Comment by pietrushnic** [comment] 2022-10-11 15:29
@zirblazer you are right we would like to stay on bleeding edge, but question is if we can afford that.

**Comment by pierinogiorgio** [comment] 2023-01-16 16:05
**Any updates?**
I'm getting an MSI Pro Z790-A with gen13 intel cpu, am I not going to be albe to use Dasharo anymore?

**Comment by miczyg1** [comment] 2023-01-16 16:13
@pierinogiorgio we will be working on MSI Pro Z790-P with gen13 CPUs starting in February. Not sure how different Pro Z690-A will be.

**Comment by pierinogiorgio** [comment] 2023-01-17 10:09
@miczyg1 I already researched the subject, the two motherboards are pretty much identical - only performance upgrades were introduced (DDR5 and gen13 cpu) in the MSI Pro Z**790**-A.
Perhaps the same Dasharo for MSI Pro Z**690**-A will work just fine.

**Comment by miczyg1** [comment] 2023-01-17 10:55
@pierinogiorgio such assumptions often led to many problems from my experience. We have done mobo pictures comparison between `-P` and `-A` variant of Z790 and the `-P` seems to be identical to Z690-A, Z790-A changed much more so I doubt it will work without issues.

> Perhaps the same Dasharo for MSI Pro Z690-A will work just fine.

I wouldn't try if I were you, not even in my place.

**Comment by pierinogiorgio** [comment] 2023-01-17 11:51
@miczyg1 Hmm, if you say so then I better trust your words and get the "old" Pro Z690-A while the latest gen is being worked out. I already ordered the DDR5 and i9-13900k though, do you see issues using those with the Pro Z690-A _from Dasharo's_ point of view I mean?

**Comment by miczyg1** [comment] 2023-01-17 11:57
If Z790-A is only about performance change, then the only difference between Z790-A and Z690-A will be how much you can overclock the CPU. Also Z790 chipset has few more PCIe 4.0 lines than Z690.

From the Dasharo perspective we only have to add Raptor Lake-S CPU support to the coreboot.

**Comment by dawidpotocki** [comment] 2023-02-01 12:34
I know that the issue is about Raptor Lake, but porting to Z790-P was mentioned here.

> [MSI's] Intel 700 BIOS ROM files support Secure Flash so they cannot be modified or altered by tools.

I don't know exactly how AMI's Secure Flash works, but I thought that this might be useful information to you.

**Comment by RedAnon** [comment] 2023-02-08 08:27
Any ETA on the Z790 support? Is it being considered for next port?

**Comment by miczyg1** [comment] 2023-02-08 09:54
@RedAnon yes, it is considered and actually confirmed to be ported. Exactly the MSI PRO Z790-P (DDR5 WiFi/non-WiFi). We will start the work on it soon.

**Comment by miczyg1** [comment] 2023-02-08 10:17
> I know that the issue is about Raptor Lake, but porting to PRO Z790-P was mentioned here.
> 
> > [MSI's] Intel 700 BIOS ROM files support Secure Flash so they cannot be modified or altered by tools.
> 
> I don't know exactly how AMI's Secure Flash works, but I thought that this might be useful information to you.
> 
> It seems to be an implementation of https://csrc.nist.gov/publications/detail/sp/800-147/final
> 
> https://uefi.org/sites/default/files/resources/UEFI_Plugfest_2012Q1_v3_AMI.pdf
> 
> > If the custom BIOS were built from other sources, it is not supported by Secure Flash and would be blocked by flash programmer.

Have you tried running flashrom on such board? I wonder what flash protections are really enabled to make it "Secure"

**Comment by dawidpotocki** [comment] 2023-02-08 10:21
> Have you tried running flashrom on such board? I wonder what flash protections are really enabled to make it "Secure"

I have not. I'm just forwarding the information that I have received directly from MSI.

**Comment by miczyg1** [comment] 2023-02-08 10:22
> > Have you tried running flashrom on such board? I wonder what flash protections are really enabled to make it "Secure"
> 
> I have not. I'm just forwarding the information that I have received directly from MSI.

Thank you for that information though. It was a little surprise.

**Comment by zirblazer** [comment] 2023-02-08 10:42
> I know that the issue is about Raptor Lake, but porting to PRO Z790-P was mentioned here.
> 
> > [MSI's] Intel 700 BIOS ROM files support Secure Flash so they cannot be modified or altered by tools.
> 
> I don't know exactly how AMI's Secure Flash works, but I thought that this might be useful information to you.
> 
> It seems to be an implementation of https://csrc.nist.gov/publications/detail/sp/800-147/final
> 
> https://uefi.org/sites/default/files/resources/UEFI_Plugfest_2012Q1_v3_AMI.pdf
> 
> > If the custom BIOS were built from other sources, it is not supported by Secure Flash and would be blocked by flash programmer.

For what I read in Win-RAID, Secure Flash seems to be about AMI flashing tools validating than the image about to be flashed has not been tampered. But flashrom shouldn't be limited by any of that.
Also note than the custom flashrom that is being used for Z690 needs to be updated with Z790 PCIID, so no need to test because it is not expected to work.

**Comment by dawidpotocki** [comment] 2023-02-08 10:58
Just to provide a bit more background, my last quote is an answer from
MSI's motherboard team to the question if external programmers would be
blocked by Secure Flash.

Now, this answer could be totally wrong and I wouldn't be even surprised
at this point based on the email conversations I had with them.

It is a bit hard for me to squeeze any information from them for some of
my questions.

**Comment by RedAnon** [comment] 2023-02-08 11:02
> @RedAnon yes, it is considered and actually confirmed to be ported. Exactly the MSI PRO Z790-P (DDR5 WiFi/non-WiFi). We will start the work on it soon.

Very nice.
I'll buy one and test it then. :)
Is it possible to build the code from master and flash it for testing already?

**Comment by miczyg1** [comment] 2023-02-08 12:18
@RedAnon, if you are brave enough, there is a WIP patchset for Raptor Lake S support on Z690 chipset https://review.coreboot.org/c/coreboot/+/69798
but there is no code support for the Z790 board itself. I don't recommend flashing Z690-A build on it, as the GPIO configuration may be different and, in the worst case, cause a short circuit and damage the board.

**Comment by miczyg1** [comment] 2023-02-12 21:50
I have completed the patch: https://review.coreboot.org/c/coreboot/+/69798

Still some minor things like PCI IDs are missing in the documentation so not all SKUs may be covered with default values (the lower end are affected).

**Comment by miczyg1** [comment] 2023-04-17 11:52
Seems like bumping the FSP submodule to have Raptor Lake support will cause build issues for other boards: https://review.coreboot.org/c/coreboot/+/74442

`I haven’t check the details yet, but from a quick glance seems like the new CCG ADL FSP updated by Nate recently broke the adl build.`

New ADL FSP (with minimal RPL support) seems to be too big

**Comment by miczyg1** [comment] 2023-07-13 08:07
Set of merged patches that implement RPL-S (13th gen) support:

https://review.coreboot.org/c/coreboot/+/69798
https://review.coreboot.org/c/coreboot/+/76203
https://review.coreboot.org/c/coreboot/+/76191
https://review.coreboot.org/c/coreboot/+/76192
https://review.coreboot.org/c/coreboot/+/76204

13th gen support will be available in a pre-built binary for subscribers in the incoming Z690-A v1.1.2 release. For non-subscribers, building from source code will also be possible.

Z790-P board patches still in review. Z790-P with 13th gen support will be available in a pre-built binary for subscribers in the incoming Z790-P v0.9.0 release. For non-subscribers, building from source code will also be possible.

**Comment by pietrushnic** [comment] 2023-07-17 15:23
@artur-rs @BeataZdunczyk I would expect the following:
* relevant position in the 3mdeb shop
* marketing campaign related to the release of NLNet milestone - I guess this would be precisely converted in some blog post
* marketing campaign of DES for a new model sold in 3mdeb shop
* marketing campaign of DES for DRS partners who would like to sell that hardware with a Dasharo subscription
  * This has to be connected with the extension of dasharo.com and information about DES, DRS etc.
* DES should cover various situations
  * those who buy hardware+DES in 3mdeb shop
  * those who buy just DES in 3mdeb shop to gain above features on new hardware
  * those who buy just DES in 3mdeb shop to gain the above features on hardware that already use open-source firmware (e.g. customer user build from Dasharo forks)

**Comment by pietrushnic** [comment] 2023-07-17 15:24
> Set of merged patches that implement RPL-S (13th gen) support:
> https://review.coreboot.org/c/coreboot/+/69798
https://review.coreboot.org/c/coreboot/+/76203
https://review.coreboot.org/c/coreboot/+/76191
https://review.coreboot.org/c/coreboot/+/76192

@miczyg1 congratulations.
https://review.coreboot.org/c/coreboot/+/76204

**Comment by BeataZdunczyk** [comment] 2023-09-07 07:57
Closing this issue as https://review.coreboot.org/c/coreboot/+/69798 has been successfully merged. Thanks to all contributors for their work!

**Closed by BeataZdunczyk** 2023-09-07 07:57 UTC
Labels: enhancement, MSI PRO Z690-A boards
