### ISSUE TITLE
Contact form on dasharo website doesn't seem to work

### ISSUE THREAD

**Issue by pietrushnic** [Dasharo/dasharo-issues#347] opened 2023-02-23 08:18 UTC
**Dasharo version**

N/A

**Dasharo variant**

N/A

**Affected component(s) or functionality**

Contacting through dasharo.com website.

**Brief summary**

After clicking submit nothing happen. Email does not get into dasharo team inbox.

**How reproducible**

Go to https://www.dasharo.com/pages/contact/ and try to submit a message.

**Expected behavior**

User is informed about the fact that message was sent (maybe even can get copy of the email, what could be configurable while sending).

**Actual behavior**

Nothing happen.

**Comment by MateuszKochner** [comment] 2023-03-17 08:56
I checked in the console at dasharo.com/pages/contact/ (F12) 
When submitting the form, an error appeared
![405](https://user-images.githubusercontent.com/119573904/225837653-368a6e1e-d8a3-4fa2-8cbb-adf69a6e16d2.png)
The problem is probably in the contactPageForm.js file 69-70 line of code.  405 status

      $.post(
        "https://dasharo.com/send",
        
suggested solution:
1) unlock access to the site "https://dasharo.com/send" (404)
2) Alternatively, there is also an $.ajax() function


![301](https://user-images.githubusercontent.com/119573904/225857921-99aa9aac-6ae9-4f9b-bb9c-f58ed8c21a9a.png)

The 301 status code indicates that a page has been permanently moved to a new location

**Comment by artur-rs** [comment] 2023-03-17 10:16
@MateuszKochner thanks for initial analysis, I'll take a look from here

**Comment by pietrushnic** [comment] 2023-09-07 11:44
@miczyg1 It already works: https://www.dasharo.com/pages/contact/ - I have issues with Firefox because of content policy (loading js from an external source). The question is how to fix that. In the future, we will move to Mautic and use its forms for contact.

**Closed** 2024-06-28 19:13 UTC
