### ISSUE TITLE
Preserve user data during firmware updates

### ISSUE THREAD

**Issue by BeataZdunczyk** [Dasharo/dasharo-issues#809] opened 2024-04-17 15:32 UTC
**Brief summary**

Some of the data should be preserved between firmware versions. This includes:

- [x] SMMSTORE - holds UEFI variables, e.g. user settings
- [x] ROMHOLE (MSI only) - required for [FlashBIOS recovery](https://docs.dasharo.com/unified/msi/recovery/#using-msi-flashbios-button)
- [x] SMBIOS - [unique data like serial number or system UUID](https://docs.dasharo.com/unified/msi/initial-deployment/#migrating-smbios-unique-data)
- [x] boot logo - [customizable by users](https://docs.dasharo.com/guides/logo-customization/)

**Comment by mkopec** [comment] 2024-09-12 14:56
in the best case, if the update driver determines FMAP to be the same in current and new versions, it can attempt to only flash code partitions (RW_SECTION_A, RW_SECTION_B, WP_RO in the Vboot case, COREBOOT in the non-vboot case). That way we preserve everything we need, and the update is faster and more reliable than attempting to transplant this data. We also get to keep the MRC cache, and we already have users complaining that the boot time after updating is long, caused by retraining. But then we'd have to somehow ensure that the FMAP never changes :)

**Comment by SergiiDmytruk** [comment] 2024-09-15 22:22
> in the best case

Not sure we can assume the best case.

> That way we preserve everything we need, and the update is faster and more reliable than attempting to transplant this data.

Don't know if it's more reliable or not.  It's patching old image vs the new one, either way incompatibilities are possible.

> We also get to keep the MRC cache

I guess it can be copied as well.

***

Since we'll need at least FMAP, I did implementation using just it [here](https://github.com/Dasharo/edk2/compare/enable-capsule-updates...preserve-fw-settings).  Also includes CBFS code, which can be compiled, but it's not used yet.  @JanPrusinowski, building from that branch should already make some tests pass.

**Comment by SergiiDmytruk** [comment] 2024-09-17 22:06
In its current state the branch copies everything in the OP, but `SMMSTORE` is copied as a region.  SMBIOS data is moving using GPL code from `cbfstool`.

Replacing EFI protocols seems to not be feasible because `VariablesDxe` caches it and the code in general isn't meant to allow dynamic replacement of that sort.  I was about to use `efivars.c` from coreboot instead, but later switched to `smmstoretool` which also has variable store creation in it.  The code compiles and runs (copying all variables), but QEMU doesn't boot afterwards.  Need to debug why.

**Comment by SergiiDmytruk** [comment] 2024-09-18 16:32
> Wouldn't it be enough to add new variables driver to capsule and let it repeat what `VariableServiceInitialize()` does

There is an event handler that needs to be triggered, global data and it also initializes libraries.  Maybe it can be made to work, but that will take more effort and doesn't really look reliable.

> I think we can leave it at copying whole region for now, and maybe leave accessing single variables as potential future improvements.

I made implementation from `smmstoretool` work.  I just missed setting one field and also didn't skip copying of volatile variables.  It's ~300 lines long.

**Comment by SergiiDmytruk** [comment] 2024-09-19 13:37
Send PR: https://github.com/Dasharo/edk2/pull/166

Regarding MRC cache. As far as I can tell, something like this should work:
```
if UNIFIED_MRC_CACHE region exists
    copy it
else
    if RECOVERY_MRC_CACHE region exists
        copy it
    copy RW_MRC_CACHE region

copy RW_VAR_MRC_CACHE region if exists ?
```

I don't know much about it and how safe it is to have these regions potentially containing incompatible garbage, but if somebody thinks it should work, it's an easy thing to add this to the PR.

**Comment by JanPrusinowski** [comment] 2024-09-24 10:21
I have created tests for: SMMSTORE, SMBIOS and boot logo
Availible: https://github.com/Dasharo/open-source-firmware-validation/pull/501

Also I used the latest release suggested by @SergiiDmytruk  - however I must have done something wrong as I didnt notice any changes from previous builds except for that the logo tests now work.
I have made some fixes so that tests will run on MSI. I have run those tests and - providing that the FW will support it test should work.

I still dont know how to create ROMHOLE data and put it into the fw. I have aed about ROMHOLETOOL in: https://github.com/Dasharo/open-source-firmware-validation/pull/501

**Comment by krystian-hebel** [comment] 2024-09-24 11:35
> however I must have done something wrong as I didnt notice any changes from previous builds except for that the logo tests now work.

Please attach logs.

**Comment by SergiiDmytruk** [comment] 2024-09-24 12:19
@JanPrusinowski Note that there is an issue in coreboot preventing it from working on MSI without extra changes (works fine in QEMU): https://github.com/Dasharo/edk2/pull/166#discussion_r1768948404.  The capsule update should just fail during an update and the fact that it didn't, shows that you probably built firmware with old revision of EDK2 (go to `payloads/external/edk2/workspace/Dasharo` and see current commit hash via `git show` or alike).  It won't work yet though even with the correct revision unless you modify coreboot locally as I did (see the comment, this primarily needs to be done for initial firmware).

Log from Jira: [capsule-preserve-data-log.zip](https://github.com/user-attachments/files/17114349/capsule-preserve-data-log.zip)

**Comment by krystian-hebel** [comment] 2024-09-24 13:18
https://github.com/Dasharo/edk2/pull/166 has been merged, but MSI requires fixes to coreboot to be able to read whole flash when it is bigger than 16 MiB.

**Comment by SergiiDmytruk** [comment] 2024-09-24 18:30
> MSI requires fixes to coreboot to be able to read whole flash when it is bigger than 16 MiB.

Pushed https://github.com/Dasharo/coreboot/pull/509/commits/8c87fbd3499cc711143e561482cf3aaf630e608d to https://github.com/Dasharo/coreboot/pull/509, can be reviewed there.

**Comment by JanPrusinowski** [comment] 2024-09-25 06:01
Logs requested by Krystian: [log(9)1.zip](https://github.com/user-attachments/files/17125793/log.9.1.zip)

**Closed** 2024-10-16 14:27 UTC
