### ISSUE TITLE
V540TND v0.9.1-rc5 cyclic suspend test fails

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dasharo-issues#1045] opened 2024-09-12 10:42 UTC
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

v0.9.1-rc5

### Dasharo Tools Suite version

--

### Test case ID

SUSP005

### Brief summary

Kernel version 6.9 (mainline):
- SUSP test fails: FAILED [CRITICAL] S2idleNotDeepest: Test 1, Expected /sys/power/suspend_stats
- Nvidia driver does not load or even build in DKMS despite having kernel headers installed
Kernel version 6.8 (Ubuntu):
- Wakeup from S0ix does not work
Kernel version 6.10 (mainline):
- does not boot

### How reproducible

100%

### How to reproduce

Install and boot kernel 6.9 w/ headers
Run SUSP005

### Expected behavior

Should pass without errors

### Actual behavior

Fails, FAILED [CRITICAL] S2idleNotDeepest: Test 1, Expected /sys/power/suspend_stats

### Screenshots

[platform-suspend-and-resume.robot_log.zip](https://github.com/user-attachments/files/16977736/platform-suspend-and-resume.robot_log.zip)
```
s3: Sleep suspend/resume test.
--------------------------------------------------------------------------------
Test 1 of 1: Sleep suspend/resume test.
Defaulted to 1 test, use --s3-multiple=N to run more s2idle cycles 
s2idle cycle 1 of 1 
Detecting the power method.
Response to CanSuspend is yes 
User allowed to execute the CanSuspend action 
Using logind as the default power method.
Requesting Suspend action 
Skipping the minimum delay (0) and using a 3 seconds delay instead 
s2idle duration = 30.
wakeup source name: "00:04" wakeup event was signaled.
pm-action returned 0 after 30 seconds.
FAILED [CRITICAL] S2idleNotDeepest: Test 1, Expected /sys/power/suspend_stats
/total_hw_sleep to increase from 0, got 0.
Suspend/Resume Timings:
  Suspend: 0.376 seconds.
  Resume:  0.661 seconds.
Completed s2idle cycle(s) 
PASSED: Test 1, No kernel log errors detected.
PASSED: Test 1, No PM related suspend issues detected.
PASSED: Test 1, No device errors detected.
PASSED: Test 1, No kernel oopses detected.
PASSED: Test 1, No kernel WARN_ON warnings detected.
Found 1 s2idle errors.
PASSED: Test 1, Found no errors doing 1 suspend/resume cycle(s).
PASSED: Test 1, All suspends took less than 15.00 seconds.
PASSED: Test 1, All resumes took less than 15.00 seconds.

================================================================================
8 passed, 1 failed, 0 warning, 0 aborted, 0 skipped, 0 info only.
================================================================================


8 passed, 1 failed, 0 warning, 0 aborted, 0 skipped, 0 info only.

Test Failure Summary
================================================================================

Critical failures: 1
 s3: Expected /sys/power/suspend_stats/total_hw_sleep to increase from 0, got 0.

High failures: NONE

Medium failures: NONE

Low failures: NONE

Other failures: NONE

Test           |Pass |Fail |Abort|Warn |Skip |Info |
---------------+-----+-----+-----+-----+-----+-----+
s3             |    8|    1|     |     |     |     |
---------------+-----+-----+-----+-----+-----+-----+
Total:         |    8|    1|    0|    0|    0|    0|
---------------+-----+-----+-----+-----+-----+-----+
```

### Additional context

@mkopec says it's probably because of missing nvidia drivers on Ubuntu on kernel 6.9 the GPU is not powered down and the device can not suspend completely. On kernel 6.8 where drivers work the device would not wake up from suspend at all because of only partial support for MTL.

**Comment by mkopec** [comment] 2024-10-03 10:38
Good S0ix residency on Ubuntu 24.10 beta, now we have but https://github.com/Dasharo/dasharo-issues/issues/1045

**Comment by wessel-novacustom** [comment] 2024-10-03 11:23
> Good S0ix residency on Ubuntu 24.10 beta, but now we have #1045

@mkopec It looks like you are referring to the wrong ticket?

**Comment by mkopec** [comment] 2024-10-03 11:25
Right, of course, meant to link https://github.com/Dasharo/dasharo-issues/issues/1018 .

**Comment by mkopec** [comment] 2024-10-16 11:06
Fixed by
- https://github.com/Dasharo/coreboot/pull/548/commits/19d804c4ce98f2db4a9afaa0a7abad6e1c7c01f9
- https://github.com/Dasharo/coreboot/pull/548/commits/29eba1f81f4a94f9923e6f5bb5b30b4508df786b

**Closed by mkopec** 2024-10-16 11:06 UTC
Labels: bug, firmware, novacustom_v54_mtl, kernel

**Comment by filipleple** [comment] 2024-10-16 16:34
I can confirm that this no longer occurs for V540TND on v0.9.1-rc7.

```
==============================================================================
Platform-Suspend-And-Resume
==============================================================================
SUSP005.001 Cyclic platform suspend and resume (Ubuntu) :: This te... ...
Checking if fwts is installed...

Package fwts is installed

15 iterations were performed to check the suspend procedure.
0 iterations have failed.
SUSP005.001 Cyclic platform suspend and resume (Ubuntu) :: This te... | PASS |
Test case SUSP005.001 Cyclic platform suspend and resume (Ubuntu) has been marked passed.
The number of detected errors is at least the same as the number of allowed fails: 0.
------------------------------------------------------------------------------
SUSP005.002 Cyclic platform suspend and resume (Ubuntu) (S0ix) :: ... | SKIP |
SUSP005.002 not supported
------------------------------------------------------------------------------
SUSP005.003 Cyclic platform suspend and resume (Ubuntu) (S3) :: Th... | SKIP |
SUSP005.003 not supported
------------------------------------------------------------------------------
Platform-Suspend-And-Resume                                           | PASS |
3 tests, 1 passed, 0 failed, 2 skipped
==============================================================================
```
