### ISSUE TITLE
No internal audio playback on V560TNE

### ISSUE THREAD

**Issue by filipleple** [Dasharo/dasharo-issues#991] opened 2024-08-12 09:52 UTC
### Component

Dasharo firmware

### Device

NovaCustom V56 14th Gen

### Dasharo version

v0.9.1-rc1

### Brief summary

No internal audio playback on V560TNE, though the HW does get detected

### How reproducible

100%

### How to reproduce

Try to play any sound from the V560TNE internal speaker

### Expected behavior

It should be audible

### Actual behavior

The speaker is dead silent even on max volume, though the hardware does get detected

**Comment by mkopec** [comment] 2024-08-12 14:01
Probably missing smartamp configuration.

**Comment by filipleple** [comment] 2024-08-12 14:38
This persists on rc2.

**Comment by mkopec** [comment] 2024-08-19 15:45
started some work on it: https://github.com/Dasharo/coreboot/pull/548/commits/e175d2becd78b514656d155e7fb9e99f59121b34

There's an issue where the 16 inch dGPU models come with a smart amp on i2c5, but 14 inch models don't. Insyde programs verbs and smartamp config depending on board id, we may need something similar.

**Comment by mkopec** [comment] 2024-08-20 13:06
right, this was addressed in https://github.com/Dasharo/coreboot/pull/548/commits/230d6038a06338d4fa52b71958c73096fffbadde and will be part of rc4

**Comment by philipandag** [comment] 2024-09-02 05:15
The internal audio works on V560TNE with rc4.

**Comment by philipandag** [comment] 2024-09-18 07:23
The internal audio was working on V540TND with v0.9.1-rc5 for a while just when I have started the tests but does not work anymore neither on Windows nor Ubuntu with kernel 6.8 and 6.9. Interestingly the [issue with HDMI audio on Windows being distorted](https://github.com/Dasharo/dasharo-issues/issues/1025) seems to be gone now.

**Comment by mkopec** [comment] 2024-10-02 13:56
Should be fixed by https://github.com/Dasharo/coreboot/commit/d7e5ec9c2f82e1fd43130adc02c32ab0f5f1283e . Appears to work on V56, waiting on a free V54 to test

**Comment by mkopec** [comment] 2024-10-02 14:14
confirmed working on V54 too, closing

**Closed by mkopec** 2024-10-02 14:14 UTC
Labels: bug, firmware, needs review, novacustom_v56_mtl

**Comment by mkopec** [comment] 2024-10-08 12:18
@SebastianCzapla can you attach logs from the failed test here?

**Comment by SebastianCzapla** [comment] 2024-10-08 12:30
Marked it as issue by a mistake, works as intended.
