### ISSUE TITLE
MSI PRO Z690-A WIFI DDR4 doesn't initialize IGP on certain Processors models

### ISSUE THREAD

**Issue by zirblazer** [Dasharo/dasharo-issues#274] opened 2022-11-29 10:36 UTC
**Dasharo version**
Dasharo 1.0.0 and 1.1.0 for MSI PRO Z690-A WIFI DDR4 and its non-WIFI and DDR5 variants.

**Affected component(s) or functionality**
Initialization of the Processor IGP during Firmware POST

**Brief summary**
A person with a Core i3 12100 reported than he had no video output from the IGP during Firmware POST stages, but that it worked after OS loaded GPU drivers. IGP was fully functional with MSI Firmware. This was forcing to suggest users having a dGPU at hand when flashing Dasharo for the first time in case than the system appears bricked due to a non functional IGP.
Bug already identified and fixed on developer builds. Intel uses multiple PCI DeviceIDs for Alder Lake-S IGPs, several were absent.

**How reproducible**
100%

**How to reproduce**
Use one of Processors with IGPs that have incomplete support. Supposedly the only PCI DeviceID recognized is 4680h, but there were two users with a 12400 that didn't reported issues, whereas one with a 12100 did. Also note than 12400 model can come in either the big 8+8 C0 die or 6+0 H0 versions, both have different DeviceID (Neither which is 4680h, so I don't know why it worked).
Full lists of Device IDs from Datasheet: https://edc.intel.com/content/www/us/en/design/ipla/software-development-platforms/client/platforms/alder-lake-desktop/12th-generation-intel-core-processors-datasheet-volume-1-of-2/009/device-ids/

S LGA 8+8 | C0 | 32EU | 4680h - Core i9 12900, 12900K, 12900KS
S LGA 8+4 | C0 | 32EU | 4680h - Core i7 12700, 12700K
S LGA 6+4 | C0 | 32EU | 4680h - Core i5 12600, 12600K
S LGA 6+0 | C0 | 24EU | 4682h - Core i3 12400 (C0 die version)
S LGA 6+0 | H0 | 32EU | 4690h - Core i5 12500, 12600
S LGA 6+0 | H0 | 24EU | 4692h - Core i3 12100, 12400 (H0 die version)
S LGA 6+0 | H0 | 16EU | 4693h - Celeron G6900, Pentium Gold G7400

Assume all non-4680h are currently broken.

**Comment by miczyg1** [comment] 2022-11-29 10:40
Possible fix: https://review.coreboot.org/c/coreboot/+/70101

**Comment by Firminator** [comment] 2022-12-01 02:23
I think I'm affected by this, but my case seems to be a bit different. I flashed my Z690 DDR4 board Friday last week and have no video output after following instructions for the initial deployment from Dasharo docs. The screen is on and there is backlight, but it basically stays black. @zirblazer I'm really thankful that you reported this here.

Some short notes:
* had full IGP with MSI BIOS
* Secure Boot was turned off in original MSI BIOS prior flashing
* original MSI BIOS was v120
* 2x 8GB DDR with no XMP enabled in the original MSI BIOS prior flashing
* Intel Core i5 i5-12600
* no dGPU used when flashing
* no NVMEs drives or SATA drives in my build yet
* used a live Ubuntu 2210 booted from USB, so I'm OS-less
* Had no problems
 1. compiling flashrom
 2. taking backup.rom (dump.rom)
 3. while flashing to v1.1.0
* system powers on fine with Dasharo, then seems to POST but no output and the Diagnostics LEDs ('EZ Debug LED') are not red. Not sure if the EZ Debug LED functionality is actually part of Dasharo firmware
* tested all different RAM sticks including the XLR8 from the tested compatibility list on the Dasharo docs site but result is always the same: black screen
* Using a USB keyboard (haven't tested PS/2 yet)
* Tested if CTRL+ALT+DEL will reset and it surprisingly works so the USB keyboard / USB controller must be initialized; I can hear the CPU fan spin up real fast briefly before it calms down to lower RPM so I assume it reboots.
* CTRL+ALT+DEL also makes the screen go OFF briefly before it turns back on (backlight is on), but it stays black, so I think it does reboot/reset the device
* tried clearing CMOS with jumper on JBAT1 but didn't change anything; screen is still black
* tried with 4 sticks, 2 sticks and 1 sticks of RAM, but doesn't help
* tried flashback functionality although it's mentioned in the Dasharo recovery docs that it will not work; confirmed it doesn't work :)
* tried booting Memtest86 from USB to see if I can get video output somehow but I don't know what the default bootorder is and if it will actually boot from USB first

Things I wanted to try:
* use the latest open-source Memtest+ since after waiting what seems like a decade development was picked up :); maybe I get IGP output here
* find a live-distro that runs off USB and doesn't need any keyboard input to load intel IGP drivers and bring up window manager; basically fully boot unattended to GUI to see if I get any output. Any suggestions for a distro that does that?

**Comment by Firminator** [comment] 2022-12-01 04:04
* just tried all three Memtest+ v6.0 version (grub, x64, and 32bit) and get no video output either
* tried random distrohopping MX19 ISO I found in my data grave but don't get any output either (it does boot fine within a few seconds on a test laptop with 11th gen i5 IGP)

**Comment by zirblazer** [comment] 2022-12-01 06:16
@Firminator 

Did you manage to get video output after booting an OS, or you couldn't boot an OS at all yet? Because you have no display, you don't really know what Dasharo is trying to boot, is very likely it ends up in the built-in UEFI Shell (Try typing while blind reboot -s to power computer off, in that case you KNOW that is on UEFI Shell).
Worst case scenario, try disconnecting all SATA / NVMe drives and try with only a booteable USB Flash Drive plugged in, but it may still be possible than it defaults to UEFI Shell. Attemping to boot something may be possible. Oh, also, avoid using the 4 USB Ports that are on a single column on the Motherboard rear I/O, they're internally wired to an USB Hub that can hang at POST.

Do you have any video card that you could use to get display? The person than has this issue is currently running a Radeon RX580 and needs to have monitor plugged there.

**Comment by Firminator** [comment] 2022-12-01 11:07
> Did you manage to get video output after booting an OS at least a single time, or you couldn't boot an OS at all yet?

Yes with stock MSI BIOS, but never with Dasharo BIOS

> is very likely it ends up in the built-in UEFI Shell (Try waiting for a minute after power on, then typing while blind reboot -s to power computer off, in that case you KNOW that is on UEFI Shell).

I'll have to try this and report back. If I end up in UEFI shell is there a way to manually tell it to boot a USB flashdrive

> Worst case scenario, try disconnecting all SATA / NVMe drives 

As I mentioned in my mental notes above I have no NVMEs drives or SATA drives in my build yet

> but it would require someone else to help you on what commands to use and how it defaults to drive enumeration.
Yeah that's what I'm afraid of. The drive enumeration is key here because if I can blindly type something in the UEFI shell then I need to know how to have the board boot from USB

> Oh, also, avoid using the 4 USB Ports that are on a single column on the Motherboard rear I/O, they're internally wired to an USB Hub that can hang at POST.

Thanks for the hint. Good to know. For ISO booting I've been using the flashback USB port or as an alternative the port above it right below the PS/2. My keyboard however has been actually plugged in the USB2 port in the 4-port column. I'll change it for future troubleshooting although I'm pretty as mentioned in my mental notes sure I can reset the box with CTRL+ALT+DEL so it must be working fine. The UEFI test (reboot -s) will tell me for sure.

> Do you have any video card that you could use to get display?

Yes. I ordered a dGPU but I'm waiting for it to arrive. However in the meantime I will try a NV RTX 3050 from another Z690 build (without Dasharo yet) that I have here and then report back.

**Comment by Firminator** [comment] 2022-12-01 11:33
just tested: typing blindly reboot -s after waiting ~5minutes doesn't reset the box while CTRL+ALT+DEL seems to work.

**Comment by zirblazer** [comment] 2022-12-01 13:16
> I'll have to try this and report back. If I end up in UEFI shell is there a way to manually tell it to boot from a USB flashdrive (let's say the flashback port)?
Yes, but you will have to navigate blind to execute bootx64.efi or some other Boot Loader file. Check this: https://linuxhint.com/use-uefi-interactive-shell-and-its-common-commands/

(Note than the command to poweroff seems to be reset -s, not reboot -s like I said before, so try again :D) 

Something like this:

fs1: (Assuming than that is how the USB Flash Drive gets mapped)
cd EFI
cd BOOT
bootx64.efi

> As I mentioned in my mental notes above I have no NVMEs drives or SATA drives in my build yet.
Did you tried the other way around, actually plugging a drive?


> However in the meantime I will try a NV RTX 3050
Do so. But please test the reset -s first, I got the command wrong.

**Comment by Firminator** [comment] 2022-12-01 21:32
just tested: typing blindly reset -s after waiting for 15 seconds shuts down the box. Hard Poweroff :) So yes your theory is right that it does drop into UEFI shell.

The 3050 is now on my table to test. That will be next.

**Comment by Firminator** [comment] 2022-12-02 02:29
@zirblazer
>("Brief summary
A person with a Core i3 12100 reported than he had no video output from the IGP during Firmware POST stages, ..."

Where did that other person report the issue? Do you have a link?

**Comment by zirblazer** [comment] 2022-12-02 03:02
> Where did that other person report the issue? Do you have a link?
Matrix chat. He reported the issue more than a month ago or so with Dasharo 1.0.0 and provided cbmem logs but never wrote a formal bug report here (Which is what I did because this was too important giving than the affected systems appears bricked). For 1.1.0 the POST debug logs reporting was improved, so miczyg finally found in cbmem logs what was going on after he flashed it and provided new logs.
Actually, the bug was identified by the time I posted here. The fix is supposed to be this: https://review.coreboot.org/c/coreboot/+/70101
Since we're all using 12600K+, we never catched than that was missing, and symptoms were what you would expect from a brick. But I recall than there was at least another guy in Matrix chat that also had no video issues, and I was already suggesting to have a dGPU at hand just in case because it didn't seemed to be isolated.

It gives me peace of mind getting this one down.

**Comment by Firminator** [comment] 2022-12-02 04:43
Thanks for providing the history of this issue.
So in other words the i5-12600 ( https://wikiless.org/wiki/Alder_Lake#Desktop_processors_(Alder_Lake-S) ) comes with Intel UHD 770 GPU ( https://wikiless.org/wiki/List_of_Intel_graphics_processing_units#Gen12 ) and certain Alderlake S CPUs contain not the default GT1 ID of the 770 IGP but rather a slightly different variation (and thus different IDs like GT1_1 and GT2 etc.). These are currently missing thus we see a black screen as the IGP can't be initialized.
Michal's patch @ https://review.coreboot.org/c/coreboot/+/70101/2/src/soc/intel/common/block/graphics/graphics.c#309 adds those and the milestone 3 v1.1.1 should fix it then.

Sounds good to me.
Again thanks for reporting this back to Github here. This was a lifesaver! I was already playing with the thought of having to externally flash and was about to ask how to connect my RPi-connected Pomona 5250 to the Z690. I don't have a RTE mentioned in the Dasharo recovery docs and am not familiar with it.

Also thanks to Michal and Pjotr and the rest of the coreboot, Dasharo and community heros to make this happen. This is so huge. I hope it gains traction!!

**Comment by pietrushnic** [comment] 2022-12-02 10:19
> Also thanks to Michal and Pjotr and the rest of the coreboot, Dasharo and community heros to make this happen. This is so huge. I hope it gains traction!!

Thanks for supporting us. Spreading the word and growing community is our main goal for 2023. I hope we can improve adoption and make whole effort sustainable.

**Comment by zirblazer** [comment] 2023-01-10 04:53
@Firminator 
If you feel ballsy... https://github.com/Dasharo/dasharo-issues/issues/151#issuecomment-1375409568

**Comment by tmburton** [comment] 2023-01-22 04:32
> @Firminator If you feel ballsy... [#151 (comment)](https://github.com/Dasharo/dasharo-issues/issues/151#issuecomment-1375409568)

FYI, v1.1.1 RC3 did fix my black screen issues with a 12400. I was getting a blank screen until the OS started booting previously.

**Comment by Firminator** [comment] 2023-01-22 16:59
Thxs man for letting me know. I actually just recovered yesterday using a WSON8 probe and the official recovery instructions.
I might give RC3 a try if I find time.

**Comment by miczyg1** [comment] 2023-02-23 09:55
Merged upstream https://review.coreboot.org/c/coreboot/+/70101 and available on v1.1.1 release

**Comment by BeataZdunczyk** [comment] 2023-03-03 13:58
Closing this issue as it has been resolved in the v1.1.1 release. Please refer to https://docs.dasharo.com/variants/msi_z690/releases/#v111-2023-02-23 for further details.

**Closed by BeataZdunczyk** 2023-03-03 13:58 UTC
