### ISSUE TITLE
Input lag / Sluggish input (touch pad input) while charging over USB-C PD charger

### ISSUE THREAD

**Issue by serpack** [Dasharo/dasharo-issues#637] opened 2023-12-17 15:16 UTC
### Device

NV41 Gen12

### Dasharo version

1.7.1 and 1.7.2-beta

### Affected component(s) or functionality

Charging / Power system. Input system. Touch pad. Some times keyboard.

### Brief summary

While charging over USB-C PD  the input gets very laggy/sluggish. Especially it is noticeable while using touch pad

### How reproducible

I manage to reproduce this behavior in 100% of times I use USB-C PD charger. Some times it happens immediately after the charger is plugged in, some times  after a minute or two.

Sluggishness disappears and reappears multiple times while the battery is charging.

Disconnecting USB-C PD charger while the input is sluggish does not immediately help. It takes a minute or two till input normalizes

### How to reproduce

1) Discharge the battery to 50-60%
2) Plug-In USB-C charger
3) Wait a while
4) ??
5) Enjoy the very sluggish cursor movement while using touch pad

### Expected behavior

Touch pad input should not be sluggish

### Actual behavior

Touch pad is sluggish.

### Additional context

I had this issue using Gentoo Linux and Ubuntu 22.04.3 LTS.

90W USB-C Charger is used

**Comment by mkopec** [comment] 2023-12-18 09:55
Hi @serpack , can you tell us what model of charger you're using? I've seen that some chargers (especially the ungrounded variety) cause static to build up and cause the touchpad to glitch like this.

You could test if that's the cause by plugging the laptop in to something grounded, like a monitor, and then plug in the charger, and see if the problem persists.

**Comment by mkopec** [comment] 2023-12-18 09:58
Possibly related to https://github.com/Dasharo/dasharo-issues/issues/265

**Comment by serpack** [comment] 2023-12-18 10:09
I use chinese no name 90w charger I got from novacustom. [Looks like this.](https://www.softhands.co.uk/image/cache/catalog/product/delta65wc-2000x2000w.jpg) To connect to the power outlet schuko cable is used. Therefor I assume the charger should be grounded.

**Comment by serpack** [comment] 2023-12-18 10:16
> Possibly related to #265

it is indeed the same issue. Sorry for double posting. I have search for similar  only in opened issues.

**Comment by wessel-novacustom** [comment] 2023-12-18 13:30
@serpack Thank you for opening your ticket!

Bad grounding is causing this issue. This can possibly be solved in either of these ways:

1. You can improve the grounding of your power source.
2. In case the problem is in the charger itself: we can supply an alternative power supply with better internal grounding to avoid this issue. In this case, please [contact us](https://novacustom.com/contact/).

As there is no way to improve this issue with firmware (@mkopec right?), please close the issue.

**Closed** 2023-12-18 20:32 UTC
Labels: bug
