### ISSUE TITLE
Intel ARC A750 Option ROM appears incompatible with Dasharo Coreboot

### ISSUE THREAD

**Issue by xlfe** [Dasharo/dasharo-issues#584] opened 2023-11-09 21:43 UTC
### Device

MSI PRO Z790 WIFI DD5

### Dasharo version

0.9.1

### Affected component(s) or functionality

Trying to enable an Intel Arc A750 with ReBAR support

### Brief summary

System never completes POST

### How reproducible

100%

### How to reproduce

Install Dasharo 0.9.1 with CONFIG_PCIEXP_DEFAULT_MAX_RESIZABLE_BAR_BITS=36 on MSI PRO Z790 WIFI DD5 and place Intel Arc A750 GPU into PCIE x5.0 slot. Enable ReBAR in Pci options in Bios config. Connect HDMI cable to Intel Arc card and HDMI monitor. Boot.

### Expected behavior

Linux Boots with ReBAR enabled and working on Intel Arc A750

### Actual behavior

Computer never gets past POST, screen output on HDMI connected to Intel Arc a750 is garbled

<img width="1121" alt="Screenshot 2023-11-07 at 6 38 02 pm" src="https://github.com/Dasharo/dasharo-issues/assets/1177787/b46a84d7-929e-4ec3-b056-76129ae140a9">

If I connect to the onboard graphics, system boots normally, but intel arc GPU is not initialised (because no display is connected?)

When I disable all Option ROMs in the bios, the system boots normally even if HDMI output from Intel ARC is connected to the display, but I get the same result as if ReBar is disabled (even though it was enabled in the bios).

### Solutions you've tried

I have upgraded the Option ROM data and code on the Intel ARC a750 GPU - same behaviour with A750 14 00 2C 04 00 00 00 00 version

**Comment by xlfe** [comment] 2023-11-09 21:48
https://github.com/Dasharo/dasharo-issues/issues/565 is related (how I got ReBar working for this card on Dasharo)

**Comment by arthurrasmusson** [comment] 2023-11-09 21:53
Can you set the following flags in grub and then dump the output of dmesg?

`GRUB_CMDLINE_LINUX="intel_iommu=on iommu=pt vfio_pci vfio mdev intel_iommu=on iommu=pt vfio_pci vfio mdev i915.force_probe=* i915.max_vfs=31 drm.debug=0xe debug pci=realloc=off split_lock_detect=off nohpet pcie_ports=native pcie_port_pm=off"`

Also are you using the upstream i915 driver or are you running Intel's out of tree module? Not sure how ReBAR option ROMs might affect this but there is some associated firmware offload that occurs after boot (when the kernel comes up).

**Comment by xlfe** [comment] 2023-11-10 01:59
Thanks so much for having a look.

`Linux nixos 6.5.7 #1-NixOS SMP PREEMPT_DYNAMIC Tue Oct 10 20:03:06 UTC 2023 x86_64 GNU/Linux`

```
$ modinfo i915
filename:       /run/booted-system/kernel-modules/lib/modules/6.5.7/kernel/drivers/gpu/drm/i915/i915.ko.xz
license:        GPL and additional rights
description:    Intel Graphics
author:         Intel Corporation
author:         Tungsten Graphics, Inc.
import_ns:      DMA_BUF
```

[dmesg.log](https://github.com/Dasharo/dasharo-issues/files/13314484/dmesg.log)
[oprom-disabled-lspci-vvv.log](https://github.com/Dasharo/dasharo-issues/files/13314485/oprom-disabled-lspci-vvv.log)
[oproms-disabled-lspci-nn.log](https://github.com/Dasharo/dasharo-issues/files/13314486/oproms-disabled-lspci-nn.log)

**Comment by xlfe** [comment] 2023-11-10 02:03
That is with ReBar enabled in the BIOS, and Oproms Disabled 

<img width="1324" alt="image" src="https://github.com/Dasharo/dasharo-issues/assets/1177787/79723f7a-f0f3-4345-ac2f-5cc23eb719b1">

**Comment by xlfe** [comment] 2023-11-10 23:25
Here's the pci layout on Coreboot vs MSI stock bios
[1coreboot-bios-lspci-vv.log](https://github.com/Dasharo/dasharo-issues/files/13323722/1coreboot-bios-lspci-vv.log)

[2msi-bios-lspci-vv.log](https://github.com/Dasharo/dasharo-issues/files/13323723/2msi-bios-lspci-vv.log)

```
$ diff 1coreboot-bios-lspci-vv.log 2msi-bios-lspci-vv.log 
1a2
> 	DeviceName: Onboard - Other
3c4
< 	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx-
---
> 	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
13,14c14,15
< 	IOMMU group: 10
< 	Region 0: Memory at 1170000000 (64-bit, prefetchable) [size=8M]
---
> 	IOMMU group: 13
> 	Region 0: Memory at 6200000000 (64-bit, prefetchable) [size=8M]
17,18c18,19
< 	Memory behind bridge: 81000000-822fffff [size=19M] [32-bit]
< 	Prefetchable memory behind bridge: 1160000000-116fffffff [size=256M] [32-bit]
---
> 	Memory behind bridge: 81000000-823fffff [size=20M] [32-bit]
> 	Prefetchable memory behind bridge: 6000000000-61ffffffff [size=8G] [32-bit]
20c21
< 	BridgeCtl: Parity+ SERR+ NoISA- VGA+ VGA16+ MAbort- >Reset- FastB2B-
---
> 	BridgeCtl: Parity- SERR+ NoISA- VGA+ VGA16+ MAbort- >Reset- FastB2B-
70,71c71,72
< 		Max snoop latency: 3145728ns
< 		Max no snoop latency: 3145728ns
---
> 		Max snoop latency: 15728640ns
> 		Max no snoop latency: 15728640ns
76,77c77,78
< 			  T_CommonMode=0us LTR1.2_Threshold=0ns
< 		L1SubCtl2: T_PwrOn=10us
---
> 			  T_CommonMode=0us LTR1.2_Threshold=34816ns
> 		L1SubCtl2: T_PwrOn=14us
88,89c89,90
< 	Interrupt: pin ? routed to IRQ 151
< 	IOMMU group: 13
---
> 	Interrupt: pin ? routed to IRQ 153
> 	IOMMU group: 16
91,92c92,93
< 	Region 2: Memory at 1160000000 (64-bit, prefetchable) [size=256M]
< 	Expansion ROM at 000c0000 [disabled] [size=128K]
---
> 	Region 2: Memory at 6000000000 (64-bit, prefetchable) [size=8G]
> 	Expansion ROM at 82000000 [disabled] [size=2M]
100c101
< 		DevSta:	CorrErr- NonFatalErr- FatalErr- UnsupReq+ AuxPwr- TransPend-
---
> 		DevSta:	CorrErr- NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
122c123
< 		Address: 00000000fee005f8  Data: 0000
---
> 		Address: 00000000fee00618  Data: 0000
131c132
< 		BAR 2: current size: 256MB, supported: 256MB 512MB 1GB 2GB 4GB 8GB
---
> 		BAR 2: current size: 8GB, supported: 256MB 512MB 1GB 2GB 4GB 8GB
133,134c134,135
< 		Max snoop latency: 3145728ns
< 		Max no snoop latency: 3145728ns
---
> 		Max snoop latency: 15728640ns
> 		Max no snoop latency: 15728640ns
```

**Comment by zirblazer** [comment] 2023-11-13 10:11
Uploading his cbmem log myself because I can see it but other people seems to not to.
[cbmem-option-roms-disabled,rebarenabled.log](https://github.com/Dasharo/dasharo-issues/files/13333697/cbmem-option-roms-disabled.rebarenabled.log)

**Comment by miczyg1** [comment] 2023-11-23 11:52
It looks like the OptionROM BAR is seen as 2MB in size, so that is not a problem. The problem begins here:

```
[DEBUG]     PCI: 02:01.0 prefmem: size: 0 align: 20 gran: 20 limit: ffffffffffffffff
[DEBUG]      PCI: 03:00.0 18 *  [0x0 - 0x1ffffffff] prefmem
[DEBUG]     PCI: 02:01.0 prefmem: size: 200000000 align: 33 gran: 20 limit: ffffffffffffffff done
[DEBUG]     PCI: 02:04.0 prefmem: size: 0 align: 20 gran: 20 limit: ffffffffffffffff
[DEBUG]     PCI: 02:04.0 prefmem: size: 0 align: 20 gran: 20 limit: ffffffffffffffff done
[DEBUG]    PCI: 01:00.0 prefmem: size: 0 align: 20 gran: 20 limit: ffffffffffffffff
[DEBUG]     PCI: 02:01.0 24 *  [0x0 - 0x1ffffffff] prefmem
[DEBUG]    PCI: 01:00.0 prefmem: size: 200000000 align: 33 gran: 20 limit: ffffffffffffffff done
[DEBUG]   PCI: 00:01.0 prefmem: size: 0 align: 20 gran: 20 limit: ffffffffffffffff
[DEBUG]    PCI: 01:00.0 24 *  [0x0 - 0x1ffffffff] prefmem
[DEBUG]    PCI: 01:00.0 10 *  [0x200000000 - 0x2007fffff] prefmem
[DEBUG]   PCI: 00:01.0 prefmem: size: 200800000 align: 33 gran: 20 limit: ffffffff done
```

The devices behind the bridge 1.0 (so the PCIe 5.0 Root Port on CPU) report prefetchable memory with 64bit limit (ffffffffffffffff), but when coreboot concludes what the devices behind this bridge need (`PCI: 00:01.0 prefmem: size: 200800000 align: 33 gran: 20` ) the limit is suddenly truncated to 32bit (ffffffff in the last line). No idea how is this possible. Could you @xlfe please upload a full log from lspci?

`sudo lspci -xxxxvvvnnk`

**Comment by miczyg1** [comment] 2023-11-23 12:19
Even if the https://github.com/Dasharo/coreboot/pull/439 fixes setting the ReBAR, there is another problem in resource allocator or a hardware bug in the ARC PCI registers information reported about BARs, which have to be confirmed with the lspci log

**Comment by xlfe** [comment] 2023-11-23 20:48
This is the log with MSI firmware. I will need to reflash Dasharo firmware first to get that version

[verbose-lspci-msi.log](https://github.com/Dasharo/dasharo-issues/files/13453361/verbose-lspci-msi.log)

**Comment by xlfe** [comment] 2023-11-23 20:49
This is the log with MSI firmware. I will need to reflash Dasharo firmware first to get that version

[verbose-lspci-msi.log](https://github.com/Dasharo/dasharo-issues/files/13453365/verbose-lspci-msi.log)

**Comment by miczyg1** [comment] 2023-11-24 12:05
Even lspci reports the prefetchable BARs as 32bit... Weird. Anyways the bits looks good and the card advertises 64bit prefetchable memory capability on graphics and bridges. The question is still unanswered though why coreboot constrains the limit to 32bits... I guess only debugging your setup will tell us more.

**Comment by miczyg1** [comment] 2023-11-27 11:13
@xlfe let's close this ticket when the binary is officially out. Then please retest, and if everything still good then close. Thanks

**Comment by BeataZdunczyk** [comment] 2024-01-10 18:01
Closing this issue as the changes have been merged. We are currently completing testing for the release, and further updates will be provided on testing issues https://github.com/Dasharo/dasharo-issues/issues/612 and https://github.com/Dasharo/dasharo-issues/issues/613.

**Closed by BeataZdunczyk** 2024-01-10 18:01 UTC
Labels: bug, MSI PRO Z690-A boards, MSI PRO Z790-P boards
